Switch to using toast instead of form alerts
silverstripe/silverstripe-asset-admin pull request #1111
Opened 2020-07-06 11:50 UTC by maxime-rainville

This PR converts some Form Alerts in asset admin to use toast notification instead.

# Parent issue
* https://github.com/silverstripe/silverstripe-admin/issues/504

# Depends on
* https://github.com/silverstripe/silverstripe-admin/pull/1068

2020-09-04 13:06 UTC, maxime-rainville commented on client/src/containers/Gallery/Gallery.js
> -    this.props.actions.gallery.setErrorMessage(null);
This bit was testing that the message were clear. That's irrelevant when using toasts.

2020-09-04 13:07 UTC, maxime-rainville commented on client/src/containers/MoveModal/MoveModal.js
> -              <a href="#" onClick={goToFolder}>{filename}</a>
The link will be replaced by a toast action

2020-09-14 21:47 UTC, Cheddam approved these changes
Looks good, ready to go once the admin PR is merged 👍

Might be a good time to bump the Composer requirements, though? Particularly the `silverstripe/admin` one?

2020-09-16 10:36 UTC, maxime-rainville commented
Just bump the admin requirements and tweak the behat test a bit.

2020-09-21 08:02 UTC, maxime-rainville commented
Build failure is pre-existing.

2020-09-30 02:35 UTC, brynwhyman commented
This is minor but can we tweak the wording of these messages slightly? There's currently a combination of pluralised and non-pluralised words.

E.g we have: 
* "Moved %s **item(s)** to %s"

But we also have:
* "%s **folders/files** were successfully deleted."
* "%s **folders/files** were successfully published."

The later example looks pretty rough when there's only one file in question as it reads as "1 folders/files were successfully deleted.". Something more like the 'Moved' wording probably makes more sense.

cc @silverstripeux

2020-10-01 01:47 UTC, emteknetnz requested changes
Need to revert including fork before merging

2020-10-01 01:47 UTC, emteknetnz commented on composer.json
> +        "silverstripe/admin": "dev-pulls/1/reactstrap-goes-boom as 1.x-dev",
Needs to be reverted

2020-10-01 01:47 UTC, emteknetnz commented on composer.json
> +    "prefer-stable": true,
Needs to be reverted

2020-10-06 02:46 UTC, emteknetnz commented on composer.json
> +        "silverstripe/admin": "dev-pulls/1/reactstrap-goes-boom as 1.x-dev",
@maxime-rainville admin pr has been merged - could you revert, push and see if travis passes
https://github.com/silverstripe/silverstripe-admin/pull/1128

2020-10-13 20:57 UTC, maxime-rainville commented on composer.json
> +        "silverstripe/admin": "dev-pulls/1/reactstrap-goes-boom as 1.x-dev",
```suggestion
        "silverstripe/admin": "^1.7",
```

2020-10-13 20:58 UTC, maxime-rainville commented on composer.json
> +    ]
```suggestion
    "prefer-stable": true
```

2020-10-14 00:50 UTC, emteknetnz approved these changes

2020-10-15 01:46 UTC, merged