FIX Strip html tags from file upload error responses
silverstripe/silverstripe-asset-admin pull request #1138
Opened 2020-09-15 00:23 UTC by emteknetnz

Fixes https://github.com/silverstripe/silverstripe-asset-admin/issues/915

No unit tests as there are none existing for the action js files, and I'm not sure how to go about testing these.  Change is probably small enough to not have them.

If you'd like me to add some then please provide some guidance for how to go about adding tests.

Error can be simulated by updating AssetAdmin.php

```php
    public function apiCreateFile(HTTPRequest $request)
    {
        http_response_code(413);
        echo '<html>my error</html>';
        die;
```

And then uploading a file via asset-admin

2020-09-15 03:40 UTC, Cheddam requested changes
@emteknetnz The goal was to produce readable error messages for users, which I'd argue simply stripping the HTML tags does not achieve. With the example in the original issue, an author would now see:

> 413 Request Entity Too Large

The author _might_ infer that this means their file was too big, but it's not exactly a clear description, and other errors may not fair as well. I think you'd be better off creating a map of HTTP error codes to author-readable messages and using those if the response is a string. If developers want to push through a custom error message, they need to make sure they return a valid JSON response with the `errors` key populated.

cc/ @silverstripe-ux - maybe you can collaborate on the error messaging?

2020-09-15 03:49 UTC, sachajudd commented
Linking to https://github.com/silverstripe/silverstripe-asset-admin/issues/895#issuecomment-692438512 as I've just added some designs with four different error messages that we'd like to add in an instance that an extension is not allowed or a file is too big etc. We can come up with a few more if need be but these should allow you to cover the most common errors.

2020-09-22 02:24 UTC, Cheddam reviewed
Looking good, one small recommended change.

2020-09-22 02:24 UTC, Cheddam commented on client/src/lib/getStatusCodeMessage.js
> +  }
I realise this will have no immediately impact besides an infinitesimal drop in performance, but for the sake of making the next developer's job easier, could you turn this into a Code => Message map?

2020-09-22 03:27 UTC, emteknetnz commented on client/src/lib/getStatusCodeMessage.js
> +  }
I'm sure the next developer can refactor that themselves =)

2020-09-23 01:52 UTC, Cheddam approved these changes

2020-09-23 01:52 UTC, merged

2020-09-23 10:05 UTC, dhensby commented
Nice work!