FIX Update used on table unit test
silverstripe/silverstripe-asset-admin pull request #1139
Opened 2020-09-30 03:11 UTC by emteknetnz

Part of https://github.com/silverstripe/silverstripe-admin/issues/1098

2020-10-21 10:16 UTC, maxime-rainville requested changes

2020-10-21 10:16 UTC, maxime-rainville commented on tests/php/Forms/UsedOnTableTest.php
> +                "link" => sprintf('%s://localhost/admin/pages/edit/show/1', $protocol),
Can we avoid explicitly referencing localhost here? Otherwise this test will only pass when your test environment is on localhost.

2020-10-21 10:16 UTC, maxime-rainville commented on code/Extensions/UsedOnTableExtension.php
> - * Hides File Links on the "Used On" tab when viewing files
Why remove the comment?

2020-10-21 19:46 UTC, emteknetnz commented on tests/php/Forms/UsedOnTableTest.php
> +                "link" => sprintf('%s://localhost/admin/pages/edit/show/1', $protocol),
I don't know.   'localhost' was part of an existing test that was works fine as is.  I don't think spending time here is worthwhile.

2020-10-21 19:47 UTC, emteknetnz commented on code/Forms/FileFormFactory.php
> +        $tab->addExtraClass('tab-used-on-table');
This should be removed, it was for the old setInterval method of tab detection.

2020-10-21 19:57 UTC, emteknetnz commented on code/Extensions/UsedOnTableExtension.php
> - * Hides File Links on the "Used On" tab when viewing files
Added back a comment

2020-10-23 02:24 UTC, maxime-rainville requested changes
Can we update `ReadFileUsageQueryCreator` so it uses the new `DataObject::findAllRelatedData()` method instead?

2020-10-23 02:24 UTC, maxime-rainville commented on tests/php/Forms/UsedOnTableTest.php
> +                "link" => sprintf('%s://localhost/admin/pages/edit/show/1', $protocol),
This fix doesn't take a lot of time to apply and it's going to save people like me who run their test suite under a different BASE_URL a lot of aggravation.

```suggestion
                "link" => Director::absoluteURL('admin/pages/edit/show/1'),
```

2020-10-27 00:31 UTC, emteknetnz commented on tests/php/Forms/UsedOnTableTest.php
> +                "link" => sprintf('%s://localhost/admin/pages/edit/show/1', $protocol),
Updated

2020-10-27 00:31 UTC, emteknetnz commented on code/Forms/FileFormFactory.php
> +        $tab->addExtraClass('tab-used-on-table');
Updated

2020-10-27 00:33 UTC, emteknetnz commented
>> Can we update ReadFileUsageQueryCreator so it uses the new DataObject::findAllRelatedData() method instead?

Is that for the count for when you're about to delete a file?  That's been split to its own card https://github.com/silverstripe/silverstripe-asset-admin/issues/1146

2020-10-27 05:01 UTC, maxime-rainville approved these changes

2020-10-29 03:51 UTC, maxime-rainville commented
Dependent PR has been merged. Just pushed a fake commit to force a new build.

2020-11-01 21:16 UTC, maxime-rainville commented
Build is not green, but we need this merge for the beta. We're confident we can get it green post beta.

2020-11-01 21:17 UTC, merged