NEW: GraphQL 4 compatibility
silverstripe/silverstripe-asset-admin pull request #1154
Opened 2020-11-02 03:08 UTC by unclecheese

Migrated from: https://github.com/silverstripe/silverstripe-asset-admin/pull/1128

2020-11-05 22:40 UTC, chillu requested changes

2020-11-05 22:42 UTC, unclecheese commented on .travis.yml
> +  - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit tests/php '' flush=1; fi
It was the only thing that got the tests working at the time. (table names were exceeding 64 chars because `table_name` was not in the config manifest).

I'll remove and see if it's still a factor.

2020-11-11 20:34 UTC, chillu requested changes

2020-11-11 20:34 UTC, chillu commented on _graphql/mutations.yml
> +'deleteFiles(IDs: [ID]!)':
This should be lowercase `IDs`?

2020-11-11 20:34 UTC, chillu commented on _graphql/queries.yml
> +'readFileUsage(IDs: [ID]!)': '[FileUsage]'
This should be lowercase `IDs`?

2020-11-11 20:34 UTC, chillu commented on _graphql/mutations.yml
> +    IDs:
This should be lowercase `IDs`?

2020-11-11 20:34 UTC, chillu commented on _graphql/mutations.yml
> +    IDs:
This should be lowercase `IDs`?

2020-11-11 20:34 UTC, chillu commented on code/GraphQL/Schema/Builder.php
> +//        $appCategories = array_keys(File::config()->get('app_categories'));
Why is this commented out?

2020-11-11 20:34 UTC, chillu commented on composer.json
> +        "silverstripe/admin": "1.x-dev",
This technically allows installing `silverstripe/admin` lower than `1.7` which was consciously bumped via https://github.com/silverstripe/silverstripe-asset-admin/commit/b17f5fda42fbc740fdee01a7cdb8627c1f04a2f6. Wouldn't a `^1.7` constraint also allow `1.x-dev`?

2020-11-12 02:20 UTC, unclecheese commented on composer.json
> +        "silverstripe/admin": "1.x-dev",
Lots of frustration getting composer to be happy, and this may be an artefact. I'll revert and see what happens.

2020-11-12 21:51 UTC, unclecheese commented on _graphql/mutations.yml
> +'deleteFiles(IDs: [ID]!)':
Because asset-admin never used scaffolding, and everything was a custom query/mutation, the graphql 4 implementation we did the same. Ideally, we should have migrated it to models, but I don't see a whole lot of value in that migration.

So because it's custom to custom, casing doesn't matter. You can be consistent across both.

2020-11-13 00:21 UTC, chillu commented on _graphql/mutations.yml
> +'deleteFiles(IDs: [ID]!)':
Talked with Aaron, we decided to fix this anyway.

2020-11-13 00:37 UTC, chillu approved these changes

2020-11-13 01:34 UTC, merged