MNT Travis shared config
silverstripe/silverstripe-asset-admin pull request #1168
Opened 2020-11-30 22:17 UTC by emteknetnz

2020-12-21 01:48 UTC, bergice requested changes
Travis build has multiple errors. Not sure if it's related to these changes or not.

2020-12-21 22:47 UTC, emteknetnz commented
@bergice yeah it's a known issue with certain versions of chrome 87 only, including the version that travis is using.  Details here https://github.com/silverstripe/silverstripe-asset-admin/issues/1163#issuecomment-744143596

We're ignoring it for now as it'll self resolve once the version of chrome auto-updates in travis

Screenshots:
- https://s3.amazonaws.com/silverstripe-travis-artifacts/silverstripe/silverstripe-asset-admin/210135274/463701785/screenshots/insert-an-image.feature_46.png
- https://s3.amazonaws.com/silverstripe-travis-artifacts/silverstripe/silverstripe-asset-admin/210135274/463701785/screenshots/multi-file-upload-field.feature_10.png

2021-01-12 21:07 UTC, emteknetnz commented
@bergice @Cheddam I'm fairly confident the issue is the version of chrome.

The [screenshot of the issue on travis](https://s3.amazonaws.com/silverstripe-travis-artifacts/silverstripe/silverstripe-asset-admin/212772353/470711128/screenshots/insert-an-image.feature_48.png) make it look as though it's filling in of the 'Alt text' field that causes the panel to scroll down and make the details button out of view on the small screen resolution that travis uses (1024x768)

However I've [taken a video](https://www.youtube.com/watch?v=tfPOeD2Dv4c&feature=youtu.be) of running the behat scenario "I can edit image in the file modal"  up to the broken step of "And I press the "Details" button" on my local and you can see that it does correctly scroll back up and click the details button correctly

So I do think we should just merge this as is with the expectation that this will correctly itself over time.

2021-01-14 22:10 UTC, merged

2021-01-14 22:29 UTC, Cheddam approved these changes