NEW Update data source used for file delete modal
silverstripe/silverstripe-asset-admin pull request #1178
Opened 2021-02-18 01:45 UTC by emteknetnz

Part of silverstripe/silverstripe-asset-admin#1146

2021-02-28 00:08 UTC, emteknetnz commented
@clarkepaul Could you review the video demo I linked above and ensure this behaves as you expect it to.

Let me know if you'd like a further demo.  Otherwise just let me know that you're happy with how things as they are as a comment on this pull-request.  Cheers.

2021-03-02 03:58 UTC, clarkepaul commented
Hey, minor change to simplify the text a bit. We were using the word _folder_ instead of _file_ .

The same change for all three scenarios... let me know if that makes sense to you, if so then I'm all good with it :)
<img width="440" alt="delete_folder_and_file" src="https://user-images.githubusercontent.com/555033/109594771-3fb43a00-7b78-11eb-8685-e97689f0a34c.png">
<img width="449" alt="Pasted_Image_2_03_21__4_47_PM" src="https://user-images.githubusercontent.com/555033/109594887-683c3400-7b78-11eb-865d-2604596663aa.png">

<img width="455" alt="delete_single_file" src="https://user-images.githubusercontent.com/555033/109594787-43e05780-7b78-11eb-8f2e-3543666ca99b.png">

2021-03-02 05:02 UTC, emteknetnz commented
Thanks for the review, it now looks like this:

![image](https://user-images.githubusercontent.com/4809037/109600015-38ddf500-7b81-11eb-8731-cc18c3d0000d.png)

I'll move this to code review now

Are you happy to sign off the design review part of this?

2021-03-02 23:13 UTC, maxime-rainville reviewed
This is just a partial review.

Main thing I'm wondering is why not update the GraphQL service to return a single number containing the total number of selected files for your current selection?

That way you could remove a bunch of frontend logic for adding all these numbers up. That was only needed because we needed a way to pick which message to show.

Also, the message looks kinda of weird when deleting empty folders.

2021-03-02 23:13 UTC, maxime-rainville commented on client/lang/src/en.json
> +    "AssetAdmin.BULK_ACTIONS_DELETE_ITEMS_CONFIRM": "Warning: You're about to delete %s file(s) which may be used in your site's content. Please carefully check the file usage to ensure they are remo
The message is displayed in an obnoxious modal. Is it not clear enough it's a warning?
```suggestion
    "AssetAdmin.BULK_ACTIONS_DELETE_ITEMS_CONFIRM": "You're about to delete %s file(s) which may be used in your site's content. Carefully check the file usage to ensure they are removed from the content areas prior to deleting them, otherwise they will appear as broken links.",
```

2021-03-02 23:23 UTC, emteknetnz commented
> Main thing I'm wondering is why not update the GraphQL service to return a single number containing the total number of selected files for your current selection?

Reason being that
- we *might* at a future date want to use the data to overlay the number of files within folder on top of the folder icons in asset-admin.
- it made it easier to update the logic on the frontend since it was reusing the old way of doing things

This is possibly pointless and over engineered though.  Happy to change if you think it's worthwhile.

2021-03-02 23:25 UTC, emteknetnz commented on _legacy/GraphQL/DescendantFileCountType.php
> + * @deprecated 4.8..5.0 Use silverstripe/graphql:^4 functionality.
I don't think it should get @internal, simply because it won't match all the other graphql3 stuff

Good point about the version number

2021-03-02 23:26 UTC, emteknetnz commented on client/lang/src/en.json
> +    "AssetAdmin.BULK_ACTIONS_DELETE_ITEMS_CONFIRM": "Warning: You're about to delete %s file(s) which may be used in your site's content. Please carefully check the file usage to ensure they are remo
@clarkepaul ?

2021-03-14 20:23 UTC, clarkepaul commented on client/lang/src/en.json
> +    "AssetAdmin.BULK_ACTIONS_DELETE_ITEMS_CONFIRM": "Warning: You're about to delete %s file(s) which may be used in your site's content. Please carefully check the file usage to ensure they are remo
Was a bit torn on this one as the "waring:" text isn't best practice but the circumstances of not reading the text could be pretty damaging. It was only there because we are being a little lazy with the visuals communicating its importance e.g. no warning icon. I've been swayed towards removing it as Max has a good point, the whole modal acts as the warning. 

FYI its also best practice to avoid using the word "please" in UIs so that is good it was removed.

2021-03-22 20:39 UTC, brynwhyman commented on client/lang/src/en.json
> +    "AssetAdmin.BULK_ACTIONS_DELETE_ITEMS_CONFIRM": "Warning: You're about to delete %s file(s) which may be used in your site's content. Please carefully check the file usage to ensure they are remo
As per @clarkepaul's comment above, this still needs actioning

2021-03-23 02:10 UTC, clarkepaul commented
My honest thought is that it doesn't need a confirm when its an empty folder, it should just delete.
It might be like that because the same pattern is used for a file? if thats the case then the header could be simplified to just "Confirm deletion" as less words and more to the point. Otherwise what @brynwhyman has mocked is okay too.

2021-03-24 20:30 UTC, brynwhyman commented
Okay, so priority order of changes (depending on effort)
a. Remove modal when deleting an empty folder
b. Change folder wording to: "Are you sure you want to delete this folder?" with a modal heading of: "Confirm deletion" ?
  *  modal heading of: "Confirm deletion" should apply to deleting files and or folders

2021-06-14 02:29 UTC, emteknetnz commented on client/src/containers/BulkDeleteConfirmation/BulkDeleteMessage.js
>    </Fragment>
`<Fragment>` is required because there are 2 `<p>` tags

2021-06-14 03:36 UTC, emteknetnz commented on client/lang/src/en.json
> +    "AssetAdmin.BULK_ACTIONS_DELETE_ITEMS_CONFIRM": "Warning: You're about to delete %s file(s) which may be used in your site's content. Please carefully check the file usage to ensure they are remo
This was previously actioned

2021-06-14 03:36 UTC, emteknetnz commented on _legacy/GraphQL/ReadDescendantFileCountsQueryCreator.php
> + * @deprecated 4.8..5.0 Use silverstripe/graphql:^4 functionality.
Updated

2021-06-14 03:37 UTC, emteknetnz commented on _legacy/GraphQL/DescendantFileCountType.php
> + * @deprecated 4.8..5.0 Use silverstripe/graphql:^4 functionality.
Updated version number

2021-06-14 06:40 UTC, emteknetnz commented
Have made the following changes:
a) Modal heading is now always "Confirm deletion"
b) When deleting a single empty folder, the message is "Are you sure you want to delete this folder?"
c) When deleting more than one empty folder, the message is "Are you sure you want to delete these folders?"

2021-06-17 02:09 UTC, emteknetnz commented
Have confirmed this DOES work correctly with GraphQL4 as well as GraphQL3

2021-06-17 02:22 UTC, clarkepaul commented
I've had a quick squiz at the end user experience with the following scenarios (file delete, empty folder delete, multiple empty folders delete, folders delete with files in them) and happy with the end result in terms of language used :).

As a side not there are issues selecting files across multiple paginated pages but that is a separate issue.

2021-06-17 23:28 UTC, maxime-rainville requested changes
> > Main thing I'm wondering is why not update the GraphQL service to return a single number containing the total number of selected files for your current selection?
> 
> Reason being that
> - we *might* at a future date want to use the data to overlay the number of files within folder on top of the folder icons in asset-admin.
> - it made it easier to update the logic on the frontend since it was reusing the old way of doing things
> 
> This is possibly pointless and over engineered though.  Happy to change if you think it's worthwhile.

My main beef is this could end up making this request substantially slower in some cases where you have thousand of files. Sounds like a big price to pay for something we might want to do.

2021-06-17 23:28 UTC, maxime-rainville commented on code/GraphQL/Resolvers/AssetAdminResolver.php
> +        if (!is_array($args['ids'] ?? 0)) {
Is the point of the `??` operator here to squash the "Undefined index" notice?

Seems like a somewhat abusive approach. I rather we did something a little more explicit like this.

```suggestion
        if (!isset($args['ids']) || !is_array($args['ids'])) {
```

2021-06-17 23:28 UTC, maxime-rainville commented on code/GraphQL/Resolvers/AssetAdminResolver.php
> +        /** @var DataList|File[] $files */
Why not put this type definitions directly above where `$files` is used for the first time?

2021-06-17 23:28 UTC, maxime-rainville commented on code/GraphQL/Resolvers/AssetAdminResolver.php
> +            throw new \InvalidArgumentException("{$class} items {$missingIds} are not found");
Does it matter all that much if our user somehow sends us IDs that don't exists?

I'm thinking of a scenario where maybe someone is about to delete some files and another user ends up deleting them just beforehand. In that scenario we would throw a nasty error for something that doesn't sound all that consequential.

2021-06-17 23:28 UTC, maxime-rainville commented on tests/php/GraphQL/Legacy/ReadDescendantFileCountsQueryCreatorTest.php
> +        TestAssetStore::activate('AssetAdminTest');
It's not clear to me you need physical files for this test to work because you're only interacting with DB records.

2021-06-18 00:11 UTC, emteknetnz commented
>> My main beef is this could end up making this request substantially slower in some cases where you have thousand of files. Sounds like a big price to pay for something we might want to do.

I'm not sure I follow

(it's been so long since I did the backend for this I may be making some incorrect assumptions)

a)
Is the concern that now the query is readying nested files, there's a risk that it will end up slower because all the addition queries required?  The only other option would be to simply not attempt to read the number of files?  The previous implementation was straight out inaccurate, so it was worse than not showing a number

b)
Or is the convern that the formatting of the output was an array of some key/values rather than just a integer?  This will have virutally zero bearing on performance.  An array with tens of thousands of values will still download very fast.  Also I think we now require this to work out only folders with no files are selected which impacts the message we show the user.

c)
Something else

@maxime-rainville Let me know which of the above you are concerned about

2021-06-18 06:05 UTC, maxime-rainville commented
Sorry ... I had a brain freeze. Was trying to make sense of my previous comments. Ran a test with 10000+ folder and got a response within 2 sec on my local ... which I think is reasonable.

Tested this locally on a plain install with/without GraphQL v4 and CWP install with/without GraphQL v4. Everything worked fine.

Just need to address my other comments.

2021-06-20 22:03 UTC, emteknetnz commented on code/GraphQL/Resolvers/AssetAdminResolver.php
> +            throw new \InvalidArgumentException("{$class} items {$missingIds} are not found");
It's so that it's consistent with how the rest of the system currently works e.g. https://github.com/silverstripe/silverstripe-asset-admin/blob/1/_legacy/GraphQL/DeleteFileMutationCreator.php#L54

2021-06-20 22:04 UTC, emteknetnz commented on code/GraphQL/Resolvers/AssetAdminResolver.php
> +        /** @var DataList|File[] $files */
Updated

2021-06-20 22:04 UTC, emteknetnz commented on code/GraphQL/Resolvers/AssetAdminResolver.php
> +        if (!is_array($args['ids'] ?? 0)) {
Updated

2021-06-20 22:04 UTC, emteknetnz commented on _legacy/GraphQL/ReadDescendantFileCountsQueryCreator.php
> +        if ($files->count() < count($ids)) {
It's so that it's consistent with how the rest of the system currently works e.g. https://github.com/silverstripe/silverstripe-asset-admin/blob/1/_legacy/GraphQL/DeleteFileMutationCreator.php#L54

2021-06-20 22:04 UTC, emteknetnz commented on _legacy/GraphQL/ReadDescendantFileCountsQueryCreator.php
> +        if (!is_array($args['ids'] ?? 0)) {
Updated

2021-06-20 22:09 UTC, emteknetnz commented on tests/php/GraphQL/Legacy/ReadDescendantFileCountsQueryCreatorTest.php
> +        TestAssetStore::activate('AssetAdminTest');
Removed

2021-06-20 23:52 UTC, maxime-rainville approved these changes
Looks good ... left some optional suggestions. Do with them as you please.

2021-06-20 23:52 UTC, maxime-rainville commented on _legacy/GraphQL/ReadDescendantFileCountsQueryCreator.php
> +        if ($files->count() < count($ids)) {
Might be nice to add a `@throws` comment to make this explicit.

2021-06-20 23:52 UTC, maxime-rainville commented on code/GraphQL/Resolvers/AssetAdminResolver.php
> +            throw new \InvalidArgumentException("{$class} items {$missingIds} are not found");
Might be nice to add a `@throws` comment to make this explicit.

2021-06-20 23:53 UTC, maxime-rainville commented
@clarkepaul Do you have any outstanding concerns with this one?

2021-06-21 02:03 UTC, clarkepaul commented
@maxime-rainville was only looking over @emteknetnz 's shoulder for the review but couldn't see any issues, so I'm happy with it.

2021-06-21 02:55 UTC, merged