NEW Add image form input to opt out of lazy loading
silverstripe/silverstripe-asset-admin pull request #1218
Opened 2021-06-23 05:46 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-assets/issues/451

2021-06-23 23:22 UTC, maxime-rainville commented on client/src/entwine/TinyMCE_ssmedia.js
> +        'data-eager-load': data.EagerLoad,
Most of the other attributes match the actual attribute that will be outputted in the `<img>` tag. I think the attribute should be called loading and store a string so the shortcode is as close as possible to the actual rendered HTML.

2021-06-23 23:46 UTC, emteknetnz commented on client/src/entwine/TinyMCE_ssmedia.js
> +        'data-eager-load': data.EagerLoad,
This is just a temporary thing for the checkbox.  Checkboxes only accept [0's and 1's ](https://github.com/silverstripe/silverstripe-framework/blob/4/src/Forms/CheckboxField.php#L15)

2021-06-23 23:50 UTC, maxime-rainville commented on client/src/entwine/TinyMCE_ssmedia.js
> +        'data-eager-load': data.EagerLoad,
Maybe use a dropdown then. Otherwise, we'll have to refactor the entire logic once we decide what actual field we're going to use.

2021-06-23 23:58 UTC, emteknetnz commented on client/src/entwine/TinyMCE_ssmedia.js
> +        'data-eager-load': data.EagerLoad,
Will keep as is - the AC is `A 'dummy' checkbox is created to enable/ disable lazy-loading`

2021-06-23 23:59 UTC, maxime-rainville commented on client/src/entwine/TinyMCE_ssmedia.js
> +        'data-eager-load': data.EagerLoad,
The point was to have a field ... not that it would be a checkbox.

2021-06-24 00:39 UTC, emteknetnz commented on client/src/entwine/TinyMCE_ssmedia.js
> +        'data-eager-load': data.EagerLoad,
It was decided during planning that we would use a checkbox as a temporary form control.  The designs currently have mixture of checkbox an non-checkbox options.  We may end up going with a checkbox option in which case it would make sense to keep this code more or less as is.  I think refactoring this now given we don't know what the final design state is would just be a potential waste of time.

2021-06-27 23:43 UTC, maxime-rainville commented on client/src/entwine/TinyMCE_ssmedia.js
> +        'data-eager-load': data.EagerLoad,
I'm the one who went to bat to get this in ACs in I'm telling you I don't care if it's a checkbox or a dropdown.

If you absolutely want a checkbox in, then make sure it saves data in the right format.

2021-06-28 00:41 UTC, emteknetnz commented on client/src/entwine/TinyMCE_ssmedia.js
> +        'data-eager-load': data.EagerLoad,
As previously mentioned - (Silverstripe) Checkboxes only accept [0's and 1's ](https://github.com/silverstripe/silverstripe-framework/blob/4/src/Forms/CheckboxField.php#L15)

So seems like we use the value 'eager' - at least that was my experience because I originally tried passing a string value before changing it to an int when I ran into this issue.

2021-06-30 23:04 UTC, bergice requested changes

2021-06-30 23:04 UTC, bergice commented on client/src/entwine/TinyMCE_ssmedia.js
> +        'data-eager-load': data.EagerLoad,
I agree we should be saving the data in the format of `loading="<string>"`. If we need to change this later and the data is saved using a different attribute and using a `bool` it will be a pain to change it.

I don't see the point in creating our own API's that handle this logic when we can just use the officially supported browser API that everyone will understand immediately out of the box.

If you just want to get this merged as is, then make sure we follow up on this later.
But to be fair, it looks like 90% of this PR is all about handling the data this way, so... Maybe we should just change it now?

2021-06-30 23:23 UTC, emteknetnz commented
The problem here is that we're blocked waiting to decide what we're doing with https://github.com/silverstripe/silverstripe-asset-admin/issues/1214

There's a few outcome from this that will affect this PR:
a) If we decide that we don't actually want this field after all, this we should just remove most of the code in this PR.
b) If we do decide that we want something, likely a drop down, then this PR should be updated to use a string value
c) If we decide that we want a checkbox (unlikely at this stage), then this code should stay as is

Since a decision hasn't been made at this stage, I'll move this issue to blocked

2021-06-30 23:32 UTC, maxime-rainville commented on client/src/entwine/TinyMCE_ssmedia.js
> +        'data-eager-load': data.EagerLoad,
ACs are not suicide packs and can be change after the fact. If no one is making the argument that it makes a difference if this use dropbox instead of a checkbox, let's just change the AC.

2021-07-27 10:14 UTC, maxime-rainville requested changes
I'm really not a big fan of having the "Loading" field on the same line as the dimension.

It looks weird on some resolution. That screen shot got taken on a 1999 pixel window
![image](https://user-images.githubusercontent.com/1168676/127133319-e55b4a31-c0d6-4479-bda9-590a4b40643c.png)

It's not clear to me there's any logical relation between the dimension and the lazy loading attribute.

It also leads to weird/hackish logic and CSS.

Unless someone wants to make a case there's substantial value in putting this field next to the dimensions, I would rather we keep this simple and just have a plain field on its own line.

2021-07-27 10:14 UTC, maxime-rainville commented on code/Forms/ImageFormFactory.php
Probably would be better if this bit of logic was in a private method for clarity.

2021-07-27 10:14 UTC, maxime-rainville commented on code/Forms/ImageFormFactory.php
> +            $dimensions = $fields->fieldByName('Editor.Placement.DimensionsLoading.Dimensions');
I suspect other people out there have attempted to customise this field and access it by its group name. Reorganising that group will force them to update their custom code.

I don't think that would be the end of the world and our semver commitment doesn't extend to field names. But we should be mindful about avoiding changing a field's name unless it can't be avoided.

If we do decide to update that field name, we should note it in the change logs.

2021-07-27 10:14 UTC, maxime-rainville commented on code/Forms/ImageFormFactory.php
> +            $dimensionsLoading = FieldGroup::create(
In a perfect world, a `FieldGroup` would be used to organise related fields together. Here, our groups are only used for layout purposes, which is not ideal.

2021-07-27 10:41 UTC, maxime-rainville commented on tests/behat/features/insert-an-image.feature
> +      Then I select "eager" from the "Form_fileInsertForm_Loading" field
Did you try this?

```suggestion
      Then I select "eager" from "Loading" input group
```

2021-07-27 10:41 UTC, maxime-rainville commented on tests/behat/features/insert-an-image.feature
> +      And I should see the "#Form_fileInsertForm_Loading option[value='eager']:checked" element
Did you try something like this?
```suggestion
      And the "Loading" field should contain "eager"
```

2021-07-27 21:41 UTC, emteknetnz commented
> Unless someone wants to make a case there's substantial value in putting this field next to the dimensions, I would rather we keep this simple and just have a plain field on its own line.

^ @clarkepaul 

Built following designs here - https://projects.invisionapp.com/share/WCMZMHHXRJV#/screens/454169956_Lazy_Loading

2021-07-28 00:48 UTC, clarkepaul commented
> Unless someone wants to make a case there's substantial value in putting this field next to the dimensions, I would rather we keep this simple and just have a plain field on its own line.

@maxime-rainville this was designed with the help of feedback from users. If placed in its own line it either pushes other important fields out of view, or if placed at the bottom is out of view and would not be seen. The idea of having the loading field close to other presentational aspect of the file made sense to be in the vicinity of each other. With alignment, width and height being the main fields people thought it related to. I'm keen to leave it where it is.

2021-07-28 05:30 UTC, maxime-rainville commented on code/Forms/ImageFormFactory.php
> +use SilverStripe\Forms\CheckboxField;
Presumably this is not needed anymore?

```suggestion
```

2021-07-28 05:37 UTC, maxime-rainville commented
If we're confident this layout provides value, I'm fine keeping it like this.

If this situation happens again in some other context, we should come up with a better more systematic way of doing this.

Otherwise, the approach is adequate for a one-off edge case. I still would like to see the CSS improved and me need to mention the new group name in the changelog.

2021-07-29 05:08 UTC, emteknetnz commented on client/src/containers/Editor/Editor.scss
> +#Form_fileInsertForm_DimensionsLoading_Holder {
I agree this is ugly CSS that's hacking elements to behave in ways they were not intended to.  However I'm really not sure how to get around doing this unfortunately.

The core issues is that the `ProportionConstraintField`, which has its own FieldGroup, was originally intended to be on a row by itself.  Now it needs to share that row with this new Loading field.  

If the Loading field was on its own row there would be no need for any of this CSS

The only way I know of to split the row between the ProportionConstraintField FieldGroup and the Loading FormField was two wrap them both in a 'DimensionsLoading' FieldGroup, which is a bit of a misuse of a FormGroup

Do you know of a different way to horizontally split these?

2021-07-29 05:11 UTC, emteknetnz commented on code/Forms/ImageFormFactory.php
> +            $dimensionsLoading = FieldGroup::create(
Agreed, though I don't know of another method to do the horizontal layout

2021-07-29 05:12 UTC, emteknetnz commented on code/Forms/ImageFormFactory.php
I don't think so, it's in one of those long function that has lots of similar looking code

2021-07-29 05:12 UTC, emteknetnz commented on client/src/entwine/TinyMCE_ssmedia.js
> +            const properties = sanitiseShortCodeProperties(obj);
Updated

2021-07-29 05:12 UTC, emteknetnz commented on client/src/entwine/TinyMCE_ssmedia.js
> +      return obj;
Updated

2021-07-29 05:12 UTC, emteknetnz commented on code/Forms/ImageFormFactory.php
> +use SilverStripe\Forms\CheckboxField;
Removed

2021-07-29 09:35 UTC, emteknetnz commented on tests/behat/features/insert-an-image.feature
> +      Then I select "eager" from the "Form_fileInsertForm_Loading" field
I tried it, it does not work

2021-07-29 09:53 UTC, emteknetnz commented on tests/behat/features/insert-an-image.feature
> +      And I should see the "#Form_fileInsertForm_Loading option[value='eager']:checked" element
Yup that works, there's another couple of css selectors in the file I changed too using field names

2021-08-02 07:00 UTC, maxime-rainville requested changes

2021-08-02 21:39 UTC, emteknetnz commented on client/src/containers/Editor/Editor.scss
> +      float: right;
@clarkepaul  `float: right` was specifically for the 'Loading' field to match the design, should it be removed to be consistent?

2021-08-02 22:41 UTC, clarkepaul commented on client/src/containers/Editor/Editor.scss
> +      float: right;
I think floating right on all of them would be good, I can't think of any labels where that wouldn't work. What I like about the right positioning is that the label of the field seems cleaner to read and the label flow into the field isn't obstructed, e.g. eye's stopping at the (?) icon.

2021-08-02 23:42 UTC, emteknetnz commented on client/src/containers/Editor/Editor.scss
> +    }
Removed

2021-08-02 23:42 UTC, emteknetnz commented on client/src/containers/Editor/Editor.scss
> +        width: 50%;
Removed

2021-08-02 23:42 UTC, emteknetnz commented on client/src/containers/Editor/Editor.scss
> +      }
Moved

2021-08-02 23:42 UTC, emteknetnz commented on client/src/containers/Editor/Editor.scss
> +        }
Removed

2021-08-02 23:42 UTC, emteknetnz commented on client/src/containers/Editor/Editor.scss
> +    margin-right: 0;
Removed

2021-08-02 23:42 UTC, emteknetnz commented on client/src/containers/Editor/Editor.scss
> +      height: 36px;
Have updated globally

2021-08-02 23:42 UTC, emteknetnz commented on client/src/containers/Editor/Editor.scss
> +      float: right;
Have changed to using float: right for everything

2021-08-03 01:20 UTC, clarkepaul commented
@emteknetnz took me through the UI following fixes and looks all good to me :) :
 - Tabbing ands focus of icon
 - Active of icon (popover open)
 - Hover of icon
 - Icon position (right) in relation to label
 - Colour variant of icon

2021-08-03 05:01 UTC, maxime-rainville commented on tests/behat/features/insert-an-image.feature
> +      Then I select "eager" from the "Form_fileInsertForm_Loading" field
Does `Then I select "eager" from "Loading" input group` do something different than `Then I select "eager" from the "Loading" field`? 

If not, than let's use the "input group" version and ditch the behat PR.

2021-08-03 05:37 UTC, maxime-rainville requested changes
Just need to confirm that we really [need that extra Behat scenario](https://github.com/silverstripe/silverstripe-asset-admin/pull/1218#discussion_r681435628).

Otherwise, everything works great.

2021-08-03 05:37 UTC, maxime-rainville commented on client/src/containers/Editor/Editor.scss
> +  #Form_fileInsertForm_Dimensions_Holder {
Raised a separate issue. https://github.com/silverstripe/silverstripe-admin/issues/1243

2021-08-03 21:44 UTC, emteknetnz commented on tests/behat/features/insert-an-image.feature
> +      Then I select "eager" from the "Form_fileInsertForm_Loading" field
`Then I select "eager" from "Loading" input group` doesn't work, so we need the keep the `Then I select "eager" from the "Loading" field` version

2021-08-04 23:07 UTC, maxime-rainville approved these changes
All is right with the world and the crooked places have been made straight.

2021-08-04 23:08 UTC, merged