FIX Always sort by folders first
silverstripe/silverstripe-asset-admin pull request #1222
Opened 2021-07-05 03:16 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-asset-admin/issues/1108

2021-07-06 01:44 UTC, emteknetnz commented on code/GraphQL/Resolvers/FolderTypeResolver.php
> -            $list = $list->alterDataQuery(static function (DataQuery $dataQuery) {
No longer required as the folder/file sorting now happens in sortChildren

2021-07-06 01:46 UTC, emteknetnz commented on tests/php/GraphQL/FolderTypeCreatorTest.php
> -    public function testItSortsChildrenOnTypeByDefault()
This test was failing because of the default sort code removed from FolderTypeResolver (GraphQL 4)

From a functional point of view, with this PR if you go to asset-admin folder now always display before files, implying that sortChildren is always run.

This unit test is not required because there isn't a real world scenario where we run the resolver without sortChildren

2021-07-13 01:46 UTC, maxime-rainville reviewed
Looking at it now, I'm thinking this might not be the best way of approaching this problem.

We're hacking our data layer to achieve a purely UX consideration. This could lead to weird results. For example, if you're trying to get file data out of the system, it will force you to sort you result with folder firs even if that's not what you are after.

I'm thinking the proper fix would be to have some sort of dynamic `isFolder` property and then update this bit to always sort by that first: https://github.com/silverstripe/silverstripe-asset-admin/blob/692697cf90b1bd395155cb82877d806400ff927b/client/src/state/files/readFilesQuery.js#L44-L46

2021-07-13 03:46 UTC, emteknetnz commented
> For example, if you're trying to get file data out of the system

Keep in mind this fix is only for asset-admin which is a UX component?.  If you're trying to get file data out of the system, you'll probably be writing a separate rest/graphql query?

> I'm thinking the proper fix would be to have some sort of dynamic isFolder property and then update this bit to always sort by that first

We've already tried that [here](https://github.com/silverstripe/silverstripe-asset-admin/pull/1130#issue-466485227) issue is that
a) dynamic implies you need to query the entire database table to work this out, and then sort the results
b) you could use ClassName column as your sort, but `Since Image extends File, i.e. "Image" is greater than "Folder" means that sorting by LastEdited, Title, etc, is now broken`

2021-07-15 05:56 UTC, maxime-rainville requested changes
I managed to get my GraphQL 3.5 to sort by a fake `isFolder` column with this https://github.com/creative-commoners/silverstripe-asset-admin/commit/04ff53630fe6b09f6d8f9e50ad79929ac6f0092b

It replaces some dodgy bits of logic with some slightly less dodgy bits of logic and doesn't require a new `ReadFileConnection`. Not sure it's worth spending more time on this thought.

Otherwise, what you have here works and is acceptable. Just need to make sure we don't support the `ReadFileConnection` class.

2021-07-15 05:56 UTC, maxime-rainville commented on _legacy/GraphQL/ReadFileConnection.php
> +class ReadFileConnection extends Connection
This needs to be @deprecated and/or @internal.

2021-07-15 06:08 UTC, emteknetnz commented on _legacy/GraphQL/ReadFileConnection.php
> +class ReadFileConnection extends Connection
Done

2021-07-15 23:39 UTC, maxime-rainville approved these changes
Looks good. Tested on GraphQL 3.5/4 and on installer/cwp-sink.

Technically we are adding an API to a patch release, but since we're deprecating it right away and this is a high impact bug, I think it's worth it.

2021-07-15 23:40 UTC, merged