Thumbnail image size improvements (requires MigrateFileTask on upgrade)
silverstripe/silverstripe-asset-admin pull request #1224
Opened 2021-07-13 14:00 UTC by purplespider

This PR ensures that CMS thumbnails are crisp and not blurry.

Thumbnails are typically displayed at a consistent size, yet, `ThumbnailGenerator` currently uses the `FitMax` resize method, which results in differently sized images. These are then currently resized and cropped in CSS (using `background-size: cover`) to make them display at a consistent size. However, due to `FitMax` this results in nearly all thumbnails being upscaled and thus displaying blurrier than they should. Very wide or tall images are most affected by this, especially in `UploadField` thumbnails.

This PR changes the default `ThumbnailGenerator` resize method from `FitMax` to `Fill` so that the resulting image is exactly the desired size, and no upscaling in CSS is necessary.

**NOTE: After this change, it is necessary to run `./vendor/bin/sake dev/tasks/MigrateFileTask generate-cms-thumbnails` to re-create the CMS thumbnails, otherwise NO thumbnails will display in the "Files" area. Open to suggestions for making this an optional change for existing sites.**

The default thumbnail dimensions for `UploadField` are also doubled from `60` to `120` to ensure `UploadField` thumbnails remain crisp on HiDPI displays.

2021-08-05 23:16 UTC, emteknetnz commented
> After this change, it is necessary to run ./vendor/bin/sake dev/tasks/MigrateFileTask generate-cms-thumbnails

Yeah that's a bit of a deal breaker right now, as is seems like we'll break all the sites :-)  We're not going to do that just to make thumbnails a little sharper

> HiDPI

What type of device are you using so that you noticed the blurry thumbnails?  Are you running the CMS on an ipad?

2021-08-05 23:17 UTC, emteknetnz requested changes
> After this change, it is necessary to run ./vendor/bin/sake dev/tasks/MigrateFileTask generate-cms-thumbnails

Yeah that's a bit of a deal breaker right now, as is seems like we'll break all the sites :-)  We're not going to do that just to make thumbnails a little sharper

> HiDPI

What type of device are you using so that you noticed the blurry thumbnails?  Are you running the CMS on an ipad?

2021-08-06 09:21 UTC, purplespider commented
> Are you running the CMS on an ipad?

Nope, I primarily use an iMac & MacBook (all Mac desktops and laptops have HiDPI displays and have had for several years now. I believe they’re also common in PC laptops).

However, the issue with many `UploadField` thumbnails looking crappy is apparent on _all_ displays, not just HiDPI ones. (I have a 2nd LoDPI display too).

# Example

Take this image:
![snickers](https://user-images.githubusercontent.com/329880/128480586-51411a58-f4d1-41e0-91b3-01ea4a28a722.jpg)

If you add it to an `UploadField` the thumbnail is barely legible on any display (try it yourself):
<img width="591" alt="Screenshot 2021-08-06 at 09 24 31@2x" src="https://user-images.githubusercontent.com/329880/128480831-0e9bcbf2-e2f1-4b4d-a7ac-1ea93fdcee2b.png">

If you change the `ThumbnailGenerator` `$method` from `FitMax` to `Fill` it now displays fine for LoDPI displays (but still less than ideal on HiDPI displays):
<img width="586" alt="Screenshot 2021-08-06 at 09 26 06@2x" src="https://user-images.githubusercontent.com/329880/128481056-3cb5272c-0f98-4735-bb02-ab1219a31018.png">

Changing `UploadField` `$thumbnail_width` and `$thumbnail_height` from `60` to `120` makes it display perfectly on both:
<img width="585" alt="Screenshot 2021-08-06 at 09 29 37@2x" src="https://user-images.githubusercontent.com/329880/128481538-4e60c3b8-8a26-4042-979d-f4a0ad97a506.png">

# Why does this happen?

The main issue here is that using `FitMax` for CMS thumbnails was clearly an error (or leftover from a legacy implementation), as this is what it currently ends up doing:

It applies `FitMax(60,60)` to the (above) image resulting in an image that has width 60 px and height 22 px:
![snickers copy](https://user-images.githubusercontent.com/329880/128481935-8e4b7097-10a8-4977-a342-b5437c723f20.jpg)

But `UploadField`'s thumbnails are displayed at 60 height and 60 width, so it has to stretch the 22 px high image to a height of 60 px:
<img width="164" height="60" alt="Screenshot 2021-08-06 at 09 29 37@2x" src="https://user-images.githubusercontent.com/329880/128481935-8e4b7097-10a8-4977-a342-b5437c723f20.jpg">

CSS then crops off the edges (using `background-size: cover`) and this is why you end up with a pixelated thumbnail:
<img width="591" alt="Screenshot 2021-08-06 at 09 24 31@2x" src="https://user-images.githubusercontent.com/329880/128480831-0e9bcbf2-e2f1-4b4d-a7ac-1ea93fdcee2b.png">

# What should it be doing?

It should be using `Fill(60,60)` instead of `FitMax(60,60)`, as this results in:
<img width="60" height="60" alt="Screenshot 2021-08-06 at 09 24 31@2x" src="https://user-images.githubusercontent.com/329880/128483443-5658356d-d7dc-4d4e-8bf0-3594ba90ebd5.png">
Which is the perfect size thumb for `UploadField` thumbnails on a LoDPI display (and if we change the width/height to 120, it's perfect for Lo and HiDPI displays).

# Going Forward

So hopefully you'll agree that this does need to be fixed at some point, and that it is more serious than just making images a bit sharper on HiDPI displays. If Silverstripe v5 was on the horizon, then it could make sense to just include these breaking changes in it, but I don't believe there is a plan for a v5 anytime soon.

I agree we should avoid breaking existing sites on update, so I see a few options:
1. We make this an opt-in change for existing sites. I'd need help with the best way to do this. I should add that it "only" breaks thumbnails in the Files tab. `UploadField` thumbnails update automatically without needing to run the migration script.
2. We find a way to stop it from breaking old thumbnails, and only apply it to newly generated thumbnails (unless the migrate task is run).
3. We make `UploadField` request that its thumbnails are generated using `Fill` but keep others using `FitMax`, so that existing thumbnails in Files don't break.

# Using Config

While I feel it's serious enough to need to be addressed permanently, I am aware that it is possible to make the changes required in `config`:
````yml
SilverStripe\AssetAdmin\Model\ThumbnailGenerator:
  method: Fill

SilverStripe\AssetAdmin\Forms\UploadField:
  thumbnail_width: 120
  thumbnail_height: 120
```` 

So maybe there is a way this config could automatically apply to new sites, and be opt-in for existing sites?

2021-08-06 21:23 UTC, emteknetnz commented
Thanks for this detailed explanation with screenshots, this is super helpful

I've tried uploading the image on a low/regular dpi screen (24 inch 1920x1080)

![image](https://user-images.githubusercontent.com/4809037/128572331-b1a8d744-b212-4417-a84c-9566a1eec6c0.png)

Compared next to one added above on the iMac HiDPI screen

![image](https://user-images.githubusercontent.com/329880/128480831-0e9bcbf2-e2f1-4b4d-a7ac-1ea93fdcee2b.png)

2021-08-06 21:53 UTC, emteknetnz commented
@purplespider I've created a parent issue for this [here](https://github.com/silverstripe/silverstripe-asset-admin/issues/1228) and which also links another issue for [retina image support](https://github.com/silverstripe/silverstripe-assets/issues/461)

2023-12-21 01:07 UTC, GuySartorelli commented
I've rebased and retargetted to `1.13` - I'm looking to see if there's an easy way to get asset admin to re-create thumbnails if the thumbnails it wants are missing (the same way everywhere else including upload fields will).

The same problem with needing to update all thumbnails (currently by saving the files, or by running a migration task as discussed above) also plagues the scenario where developers choose to change this same configuration in their project, so definitely is a bug we should look to fix if feasible.

2023-12-21 01:36 UTC, GuySartorelli commented
And updated unit tests to match the new file names.

2023-12-21 01:39 UTC, michalkleiner commented
It's not just the UI that can run the gql requests, right? It would be limited to logged-in users, but could still be a DDoS/performance degradation vector if queried without the limits? 
Saying that — I think there was a reason why it was explicitly turned off for these requests.

2023-12-21 01:40 UTC, michalkleiner commented
I'd be probably ok with this in a minor and mention in a changelog.

2023-12-21 01:49 UTC, GuySartorelli commented
> It's not just the UI that can run the gql requests, right? It would be limited to logged-in users, but could still be a DDoS/performance degradation vector if queried without the limits?

Let me take a look into that - that's a good point.

2023-12-21 03:03 UTC, GuySartorelli commented
I've added a new commit which aims to limit the scope of which files we're allowed to generate thumbnails for - each GraphQL query should now only be allowed to generate thumbnails for up to 100 files, which is 2x the current asset admin page limit.
That number is fairly arbitrary so I'm quite happy to set it to use the asset admin page limit - but for now I'm just doing this to check:
@michalkleiner Do you think this new change sufficiently mitigates the potential attack vector?

I've also retargetted and rebased for the `2` branch since this now adds API and therefore has to be released in a minor.

2023-12-21 10:16 UTC, michalkleiner commented
Looks ok to me but I'd prefer if there was another pair of eyes over this.

2023-12-21 21:29 UTC, GuySartorelli commented
Sweet. I've updated to use the `AssetAdmin.page_length` config and fixed tests - I'll get someone else in the team to give this a review.

2024-02-22 03:03 UTC, sabina-talipova reviewed
Looks good, just small question.

2024-02-22 03:03 UTC, sabina-talipova commented on code/GraphQL/Resolvers/FileTypeResolver.php
> +            $origGenerates = $generator->getGenerates();
Just tiny question, should we have `$origGenerates` declaration in `if` block? This question just in case, if in the future we will have additional logic in this method.

2024-02-22 03:03 UTC, sabina-talipova commented
**Upload field:**

![Screenshot_2](https://github.com/silverstripe/silverstripe-asset-admin/assets/87288324/e6ed89c7-48e8-49b0-9d54-43d46745567d)

**Image gallery (List view):**

![Screenshot_1](https://github.com/silverstripe/silverstripe-asset-admin/assets/87288324/5e8e6022-3a27-412f-b6dc-f065e9dbd9cb)

I'm not entirely sure that this is important or that anyone will notice it, but there is a slight difference between how the preview is displayed when viewing in list mode in the "Files" section. I personally like PR version a lot, but what about the user’s expectations.
And one more small clarification. I have no problems displaying previously generated thumbnails with new solution. Should we still make changes to the documentation regarding migration from one version to another? And also indicate that the default method for generating thumbnails has now changed from "FitMax"  to "Fill", as well as their minimum size.

2024-02-22 03:05 UTC, ChloeSartorelli commented
> I'm not entirely sure that this is important

Good spotting! That is important. I hadn't noticed it in my testing but yeah we don't want to give false representations of what images look like.

I'll take a gander at what we can do about that.

2024-02-22 22:47 UTC, GuySartorelli commented
That's made me realise this change would affect anyone who's using `ThumbnailGenerator` to generate their own front-end thumbnails as well.

I think what we really need is a way to declare different thumbnails depending on the context - so we would use `Fill` or `FillMax` for the gallery view and upload field, but use `FitMax` for the list view and by default for any other usage (e.g. on the frontend).

This PR isn't doing that, and I think that would be a lot of work.
I'm going to close this PR for now.

@purplespider if you'd like to persue this further lets continue discussion in the issue, get a way forward we're all happy with, and then open a new PR from there.

2024-02-22 22:47 UTC, closed without merging