DEP Update JS dependencies
silverstripe/silverstripe-asset-admin pull request #1242
Opened 2021-11-22 02:48 UTC by emteknetnz

Issue https://github.com/silverstripeltd/product-issues/issues/505

This isn't yet working, file section don't load

`Uncaught TypeError: t.fn is undefined`

Works with `yarn dev` instead of `yarn build` though strangely

Got the following warnings when building

```
    console.error node_modules/react-dom/cjs/react-dom.development.js:88
      Warning: `Injector` uses `getDerivedStateFromProps` but its initial state is undefined. This is not recommended. Instead, define the initial state by assigning an object to `this.state` in the constructor of `Injector`. This ensures that `getDerivedStateFromProps` arguments have a consistent shape.
          in Injector (created by Editor)
          in div (created by Editor)
          in div (created by Editor)
          in Editor
    console.error node_modules/react-dom/cjs/react-dom.development.js:88
      Warning: Injector.getDerivedStateFromProps(): A valid state object (or null) must be returned. You have returned undefined.
          in Injector (created by Editor)
          in div (created by Editor)
          in div (created by Editor)
          in Editor
```

```
    console.error node_modules/react/cjs/react.development.js:315
      Warning: Each child in a list should have a unique "key" prop.
      
      Check the render method of `ThumbnailView`. See https://fb.me/react-warning-keys for more information.
          in n (created by ThumbnailView)
          in ThumbnailView
```

```
    console.error node_modules/react-dom/cjs/react-dom.development.js:88
      Warning: `Injector` uses `getDerivedStateFromProps` but its initial state is undefined. This is not recommended. Instead, define the initial state by assigning an object to `this.state` in the constructor of `Injector`. This ensures that `getDerivedStateFromProps` arguments have a consistent shape.                                        
          in Injector (created by Gallery)
          in div (created by Gallery)
          in Gallery
    console.error node_modules/react-dom/cjs/react-dom.development.js:88
      Warning: Injector.getDerivedStateFromProps(): A valid state object (or null) must be returned. You have returned undefined.                                                                                                     
          in Injector (created by Gallery)
          in div (created by Gallery)
          in Gallery
```

```
    console.error node_modules/react-dom/cjs/react-dom.development.js:88
      Warning: `Injector` uses `getDerivedStateFromProps` but its initial state is undefined. This is not recommended. Instead, define the initial state by assigning an object to `this.state` in the constructor of `Injector`. This ensures that `getDerivedStateFromProps` arguments have a consistent shape.
          in Injector (created by AssetAdmin)
          in div (created by AssetAdmin)
          in div (created by AssetAdmin)
          in AssetAdmin
    console.error node_modules/react-dom/cjs/react-dom.development.js:88
      Warning: Injector.getDerivedStateFromProps(): A valid state object (or null) must be returned. You have returned undefined.                                                                                                     
          in Injector (created by AssetAdmin)
          in div (created by AssetAdmin)
          in div (created by AssetAdmin)
          in AssetAdmin

```

2021-11-23 05:33 UTC, maxime-rainville requested changes

2021-11-23 05:33 UTC, maxime-rainville commented on yarn.lock
> -  version "5.7.0"
Try pinning `dropzone` to `5.7.2` in `package.json`. It works for me when I do that. 

`5.7.3` was broken in a different way.
`5.7.4` and above cause the issue we are seeing.

Might be worth looking at the [dropzone changelog](https://github.com/dropzone/dropzone/blob/main/CHANGELOG.md#574) to see what has changed in 5.7.3/5.7.4. Otherwise we'll never be able to progress beyond `5.7.2`.

2021-11-23 21:01 UTC, emteknetnz commented on yarn.lock
> -  version "5.7.0"
OK that fixed the issue in as much as asset-admin works.  Those warnings are still there, though I supposed there are ignorable for now, just something that will presumably need to be sorted before we upgrade to react 17

2021-11-24 01:05 UTC, maxime-rainville approved these changes
LGTM

2021-11-24 01:05 UTC, merged