NEW Use embed/embed v4
silverstripe/silverstripe-asset-admin pull request #1254
Opened 2022-02-28 22:55 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-framework/issues/10243

Requires https://github.com/silverstripe/silverstripe-framework/pull/10244

2022-03-11 03:33 UTC, maxime-rainville requested changes

2022-03-11 03:33 UTC, maxime-rainville commented on code/Exceptions/InvalidUrlException.php
> +class InvalidUrlException extends Exception
Why are we creating this exception?

2022-03-11 03:33 UTC, maxime-rainville commented on code/Forms/RemoteFileFormFactory.php
> +use SilverStripe\AssetAdmin\Exceptions\InvalidUrlException;
Seems like we should be swapping this for `NetworkException` or `RequestException`?

2022-03-11 03:33 UTC, maxime-rainville commented on code/Forms/RemoteFileFormFactory.php
Is this thing use when we hotlink to a file?

2022-03-13 20:57 UTC, emteknetnz commented on code/Forms/RemoteFileFormFactory.php
Yes?

2022-03-13 21:12 UTC, emteknetnz commented on code/Forms/RemoteFileFormFactory.php
> +use SilverStripe\AssetAdmin\Exceptions\InvalidUrlException;
The RequestException implementation in embed/embed doesn't actually allow for custom messages, despite it being int he constructor.  We have a bunch of existing _t() data that we should retain.

https://github.com/oscarotero/Embed/blob/master/src/Http/RequestException.php#L16

2022-03-13 21:12 UTC, emteknetnz commented on code/Exceptions/InvalidUrlException.php
> +class InvalidUrlException extends Exception
Commented in reply below

2022-03-14 00:46 UTC, emteknetnz commented on code/Forms/RemoteFileFormFactory.php
> +use SilverStripe\AssetAdmin\Exceptions\InvalidUrlException;
Also the RequestException has 3 params, int $code and RequestInterface $request

We could make up a code, but we have no way to get $request from many contexts, eg

**RemoteFileFormFactory.php**

```php
    /**
     * Checks if the embed generated is not just a link
     *
     * @param Embeddable $embed
     * @return bool
     * @throws InvalidUrlException
     */
    protected function validateEmbed(Embeddable $embed)
    {
        if (!$embed->validate()) {
            throw new InvalidUrlException(_t(
                __CLASS__.'.ERROR_EMBED',
                'There is currently no embeddable media available from this URL'
            ));
        }
        return true;
    }
```

2022-03-16 09:42 UTC, maxime-rainville requested changes
`InvalidUrlException` sound too generic for something that is very `oEmbed` specific. At the very least, there should be a comment on the class to explain its purpose.

I'm wondering if it wouldn't make more sense to have this exception in framework instead?

2022-03-16 09:42 UTC, maxime-rainville commented on code/Forms/RemoteFileFormFactory.php
> +use SilverStripe\AssetAdmin\Exceptions\InvalidUrlException;
Cool ... that makes sense.

2022-03-16 20:58 UTC, emteknetnz commented
Have renamed to `InvalidRemoteUrlException`

Note there's something of an unavoidable (semver breaking?) API change in that the Exception thrown has changed.  It's unavoidable because the old Exception came from embed/embed v3, which no longer exists.

2022-03-19 09:24 UTC, maxime-rainville requested changes

2022-03-19 09:24 UTC, maxime-rainville commented on code/Exceptions/InvalidRemoteUrlException.php
> +class InvalidRemoteUrlException extends Exception
Can we include a comment to explains what this is for?

2022-03-20 19:41 UTC, emteknetnz commented on code/Exceptions/InvalidRemoteUrlException.php
> +class InvalidRemoteUrlException extends Exception
Added

2022-03-23 07:58 UTC, maxime-rainville approved these changes

2022-03-25 03:44 UTC, maxime-rainville commented
Build is failing because it's still trying to install an older version of frameworktest.

I took the liberty to bump it up

2022-03-25 04:05 UTC, maxime-rainville commented
Actually, the framewortest version got fixed in https://github.com/silverstripe/silverstripe-asset-admin/pull/1259 already. I removed my extra commit, merged up the other fixed and rebased.

2022-03-29 10:57 UTC, merged