FIX Show correct error message instead of successful message if file …
silverstripe/silverstripe-asset-admin pull request #1273
Opened 2022-05-30 02:58 UTC by sabina-talipova

### Description

### Parent issue

#1248

2022-05-31 23:46 UTC, GuySartorelli requested changes
Works well locally, a few things here to tidy up.

2022-05-31 23:46 UTC, GuySartorelli commented on client/src/components/PreviewImageField/PreviewImageField.js
> +    } else if (progress === 100 && !errors) {
```suggestion
    } else if (progress === 100) {
```
We don't need to check again if there are errors since this is an `else if` after we already checked that.

2022-05-31 23:46 UTC, GuySartorelli commented on tests/behat/src/FixtureContext.php
> +     * @Given /^a maximum file size is "([^"]+)"$/
```suggestion
     * @Given /^the maximum file size is "([^"]+)"$/
```

2022-05-31 23:46 UTC, GuySartorelli commented on tests/behat/features/replace-file.feature
> +    Given a maximum file size is "5k"
```suggestion
    Given the maximum file size is "5k"
```

2022-05-31 23:46 UTC, GuySartorelli commented on tests/behat/src/FixtureContext.php
> +$uploadValidatorClass:
```suggestion
SilverStripe\Assets\Upload_Validator:
```
This isn't dynamic - it will never change. There's no need to inject it into the string like that.
You _might_ need to escape the backslashes.

2022-05-31 23:46 UTC, GuySartorelli commented on tests/behat/src/FixtureContext.php
> +        $uploadValidatorClass = Upload_Validator::class;
```suggestion
```

2022-05-31 23:46 UTC, GuySartorelli commented on tests/behat/src/FixtureContext.php
> +use SilverStripe\Assets\Upload_Validator;
```suggestion
```

2022-05-31 23:46 UTC, GuySartorelli commented on client/src/components/PreviewImageField/PreviewImageField.js
> +    }
```suggestion
```
This part isn't needed - and in fact stops this function from performing its intended function. For very large files (where large files are allowed), this function provides the current upload progress to a progress bar.

2022-05-31 23:46 UTC, GuySartorelli commented on client/src/components/PreviewImageField/PreviewImageField.js
> +    } else if (errors) {
In what situation is there a `message` value? Would it make sense for `if (errors)` to come first?

2022-05-31 23:46 UTC, GuySartorelli commented on client/src/components/PreviewImageField/PreviewImageField.js
> +          {errors.value}
```suggestion
    } else if (errors) {
    const errorMessage = errors.value ? errors.value : i18n._t('AssetAdmin.DROPZONE_RESPONSE_ERROR', 'Server responded with an error.');
      messageBox = (
        <div className={`preview-image-field__message preview-image-field__message--${errors.type}`}>
          {errorMessage}
```
Sometimes there is no error message in the response, for example if you upload a file that is within the size limits in yml config, but too large for php upload limits.

2022-05-31 23:46 UTC, GuySartorelli commented on tests/behat/features/replace-file.feature
> +      And the "Name" field should contain "file1.jpg"
Check for the error message as well.

2022-05-31 23:46 UTC, GuySartorelli commented on tests/behat/src/FixtureContext.php
> +YAML;
```suggestion
        ---
        name: fileallowedsize
        ---
        $uploadValidatorClass:
            default_max_file_size:
                '*': $size
        YAML;
```
Heredocs and nowdocs don't need to be aligned to the very left side anymore - we can keep them indented with the rest of the code.

2022-06-02 21:50 UTC, GuySartorelli requested changes
There are a few small formatting changes to make plus some questions for things I don't quite understand.

2022-06-02 21:50 UTC, GuySartorelli commented on client/src/components/PreviewImageField/PreviewImageField.js
> +      : i18n._t('AssetAdmin.DROPZONE_RESPONSE_ERROR', 'Server responded with an error.');
```suggestion
        ? errors.value
        : i18n._t('AssetAdmin.DROPZONE_RESPONSE_ERROR', 'Server responded with an error.');
```
Indent these to make it easier to scan-read - they're part of the same const assignment as the line above.

2022-06-02 23:19 UTC, sabina-talipova commented on client/src/components/PreviewImageField/PreviewImageField.js
> +    } else if (progress === 100 && status === 'success') {
If there is progress less then 100, but more then 0, we process it there https://github.com/silverstripe/silverstripe-asset-admin/blob/b4dcd712f5d9bd0603f2d8e4e48a03d0a297e678/client/src/components/PreviewImageField/PreviewImageField.js#L305
and render it there https://github.com/silverstripe/silverstripe-asset-admin/blob/b4dcd712f5d9bd0603f2d8e4e48a03d0a297e678/client/src/components/PreviewImageField/PreviewImageField.js#L351

In the current code we are not processing any other situations. And how I can see in back end we don't have any other response than 4XX error responses.

I'm not sure that it's possible situation when status to be 'success' but progress to be something other than 100. Since  progress is computed by Dropzone.js and "success" status is the result of response from the server. It means if this situation is happining we could rise defect for Dropzone. 

Any way, we cannot provide the users with correct message in this situation. I'll add else condition for this case.

2022-06-03 00:17 UTC, sabina-talipova commented on client/src/components/PreviewImageField/PreviewImageField.js
> +    } else if (message) {
I suppose it's a redundant value. I think it was created for error messages initially. I couldn't find whence we send this value to Preview Image Field. I'll do more tests and if I couldn't find the code where we create this message I'll add new ticket to refactoring this part.

2022-06-03 00:19 UTC, GuySartorelli commented on client/src/components/PreviewImageField/PreviewImageField.js
> +    } else if (message) {
If you can't find it, please move this to be _before_ the success check (which is where it was previously), but _after_ the error check (error messages should take precedence imo)

2022-06-03 00:32 UTC, sabina-talipova commented on client/src/components/PreviewImageField/PreviewImageField.js
> +    } else if (progress === 100 && status === 'success') {
I haven't add additional ELSE condition, since it works up when we just load preview already existing file.

2022-06-08 21:14 UTC, GuySartorelli requested changes
Looks good.

Sorry that I only just noticed, but this should be targetting the `1.10` branch (since 1.11 isn't out yet, and this bug fix doesn't include any API changes)

2022-06-09 03:11 UTC, closed without merging

2022-06-09 03:11 UTC, sabina-talipova commented
WRONG BRANCH