FIX Include default_sort in sortChildren method
silverstripe/silverstripe-asset-admin pull request #1282
Opened 2022-07-25 06:57 UTC by emteknetnz

Issue https://github.com/silverstripe/gha-ci/issues/37

Not sure why this wasn't showing up on the travis graphql 4 behat jobs, as I was able to replicate this locally using both php 8.1 with mysql 8 as well as php 7.4 with mysql 5.7.  I replicated by creating a pair of folders 'xsubfolder1' and 'zsubfolder2' then renaming them to 'zsubfolder1' and 'xsubfolder2' respectively.  They should have then sorted by 'xsubfolder2', 'zsubfolder1' but they did not

This issue was not replicatable using graphql3, so this PR matches the graphql3 behaviour.

2022-07-25 21:28 UTC, GuySartorelli commented
> this PR matches the graphql3 behaviour

Just to clarify, did you take any code from the `legacy/graphql` directory for this, or did you look at the way this behaves with GraphQL3 and replicate that behaviour with new code?

2022-07-25 21:53 UTC, emteknetnz commented
I looked at the GraphQL 3 behavior and copied that

2022-07-25 22:06 UTC, GuySartorelli requested changes
There are some considerations in the GraphQL3 implementation that are not taken into account here, such as custom aggregate sort fields: https://github.com/silverstripe/silverstripe-asset-admin/blob/17163c8519d84001d4f50436fee72da505425cca/_legacy/GraphQL/FolderTypeCreator.php#L185-L188

It might be worth considering using the existing GraphQL3 logic which preserves _all_ existing sort orders (including default sort which is applied in `DataObject::get()`).

The `sortChildren()` method has `?Sortable` as its type for `$list` but I think it would be safe to bump this to `?DataList` since we know this admin section only handles `DataList` anyway - alternatively, you could do a `if ($list instanceof DataList)` check and do it the gql3 way if true, and this new way if false.

https://github.com/silverstripe/silverstripe-asset-admin/blob/17163c8519d84001d4f50436fee72da505425cca/_legacy/GraphQL/FolderTypeCreator.php#L180-L209

2022-07-25 23:00 UTC, emteknetnz commented on code/GraphQL/Resolvers/FolderTypeResolver.php
> +                preg_match('#^"?([a-zA-Z0-9_]+)"?( asc| desc| ASC| DESC|)$#', $defaultSort, $matches)
I find it easier to read if we avoid modifiers

2022-07-25 23:02 UTC, emteknetnz commented on code/GraphQL/Resolvers/FolderTypeResolver.php
> +            // Does not support "Table"."Field" syntax or arrays
I don't know.  I'm only doing a fairly minimal implementation that only really covers the default scenario.  I'd actually rather hardcode this the just $field == "Name" then try to get a full solution.  Context here is we're trying to get a new CI rolled out, not do enhancements

2022-07-25 23:03 UTC, emteknetnz commented on code/GraphQL/Resolvers/FolderTypeResolver.php
> +                preg_match('#^"?([a-zA-Z0-9_]+)"?( asc| desc| ASC| DESC|)$#', $defaultSort, $matches)
I think so? Are there any other characters you can think of?

2022-07-25 23:07 UTC, GuySartorelli commented on code/GraphQL/Resolvers/FolderTypeResolver.php
> +            // Does not support "Table"."Field" syntax or arrays
It's not an enhancement though. If the graphql implementation handles this better and with more flexibility, then this PR is actually fixing a regression.

2022-07-25 23:12 UTC, GuySartorelli commented on code/GraphQL/Resolvers/FolderTypeResolver.php
> +                preg_match('#^"?([a-zA-Z0-9_]+)"?( asc| desc| ASC| DESC|)$#', $defaultSort, $matches)
I have just tested creating a field called ``some-field!@#$%^&*()_+-=/?.>,<;:]}[{\|`~``
> Field SiteTree.some-field!@#$%^&*()_+-=/?.>,<;:]}[{\|`~: created as varchar(255) character set utf8mb4 collate utf8mb4_unicode_ci

I can see it in the database. Looks like we don't have any invalid characters (there are other characters I didn't try obviously but at this point it seems safe to assume basically anything is fair game)

2022-07-25 23:21 UTC, emteknetnz commented on code/GraphQL/Resolvers/FolderTypeResolver.php
> +                preg_match('#^"?([a-zA-Z0-9_]+)"?( asc| desc| ASC| DESC|)$#', $defaultSort, $matches)
This is going to get to complex, I'm going to hardcode to "Name"

2022-07-25 23:23 UTC, GuySartorelli commented on code/GraphQL/Resolvers/FolderTypeResolver.php
> +                preg_match('#^"?([a-zA-Z0-9_]+)"?( asc| desc| ASC| DESC|)$#', $defaultSort, $matches)
I'd rather just leave the test failing in that case honestly. The test should be checking that the sort functionality works as expected, rather than that some hardcoded sort is applied.

2022-07-26 00:13 UTC, emteknetnz commented on code/GraphQL/Resolvers/FolderTypeResolver.php
> +                preg_match('#^"?([a-zA-Z0-9_]+)"?( asc| desc| ASC| DESC|)$#', $defaultSort, $matches)
Integrated in the graphql 3 code so default_sort is respected

2022-07-26 01:05 UTC, GuySartorelli requested changes

2022-07-26 01:05 UTC, GuySartorelli commented on code/GraphQL/Resolvers/FolderTypeResolver.php
>          return function (?Sortable $list, array $args) use ($fieldName) {
I think we can be pretty darn confident this is a `DataList`, unless you found a situation in which that's not true?
I've just spent a little time getting familiar with the order in which things are processed for the queries that use this resolver - the `$list` here is literally the same list returned from the `resolveFolderChildren()` method which is a `DataList`.
The _only_ way this would cease being true is if someone injects a new resolver (which for some reason returns a different `List` class) _inbetween_ the main folder type resolver and the sorter plugin resolver. Plugins appear to be loaded in the order they're defined, so that would require them to _entirely override_ the graphql plugin schema for folders which seems extremely unlikely and probably isn't something we want to actively support anyway.

I'd say either explicitly declare here that `$list` is a `DataList` or at the very least throw an exception below that says other `List` classes aren't supported.

2022-07-26 01:05 UTC, GuySartorelli commented on code/GraphQL/Resolvers/FolderTypeResolver.php
> +                    //$sort[$normalised] = $dir;
```suggestion
```

2022-07-26 01:05 UTC, GuySartorelli commented on code/GraphQL/Resolvers/FolderTypeResolver.php
> +                // $sort = [];
```suggestion
```

2022-07-26 01:13 UTC, emteknetnz commented on code/GraphQL/Resolvers/FolderTypeResolver.php
>          return function (?Sortable $list, array $args) use ($fieldName) {
Changed param type to DataList

2022-07-26 01:13 UTC, emteknetnz commented on code/GraphQL/Resolvers/FolderTypeResolver.php
> +                // $sort = [];
updated

2022-07-26 01:13 UTC, emteknetnz commented on code/GraphQL/Resolvers/FolderTypeResolver.php
> +                    //$sort[$normalised] = $dir;
updated

2022-07-26 01:17 UTC, GuySartorelli approved these changes

2022-07-26 01:17 UTC, GuySartorelli approved these changes
Looks good, merge on green

2022-07-26 02:29 UTC, merged