[WIP] API Strongly-type action method signatures
silverstripe/silverstripe-asset-admin pull request #1300
Opened 2022-10-10 03:08 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-framework/issues/10466

2022-10-13 21:50 UTC, GuySartorelli requested changes

2022-10-13 21:50 UTC, GuySartorelli commented on code/Controller/AssetAdmin.php
> +    public function legacyRedirectForEditView(HTTPRequest $request): HTTPResponse
This method isn't actually returning the redirect

2022-10-13 21:50 UTC, GuySartorelli commented on code/Controller/AssetAdmin.php
> +    public function legacyRedirectForEditView(HTTPRequest $request): HTTPResponse
But also this method should probably be removed in cms5 anyway

2022-10-13 21:50 UTC, GuySartorelli commented on code/Controller/AssetAdmin.php
> +    public function unpublish(array $data, Form $form): HTTPResponse
This method has some `return null;` statements

2022-10-13 21:50 UTC, GuySartorelli commented on code/Controller/AssetAdmin.php
>          return $this->saveOrPublish($data, $form, true);
Also need to make sure that method has the typehints

2022-10-13 21:50 UTC, GuySartorelli commented on code/Controller/AssetAdmin.php
>          return $this->getRecordUpdatedResponse($record, $form);
That method also needs the typehints

2022-10-13 21:50 UTC, GuySartorelli commented on code/Controller/AssetAdmin.php
> +    public function addtocampaign(array $data, Form $form): HTTPResponse
This method has some `return null;` statements

2022-10-17 05:09 UTC, emteknetnz commented on code/Controller/AssetAdmin.php
> +    public function legacyRedirectForEditView(HTTPRequest $request): HTTPResponse
Updated to return the redirect

2022-10-17 05:10 UTC, emteknetnz commented on code/Controller/AssetAdmin.php
> +    public function unpublish(array $data, Form $form): HTTPResponse
Updated

2022-10-17 05:11 UTC, emteknetnz commented on code/Controller/AssetAdmin.php
>          return $this->saveOrPublish($data, $form, true);
The strong types in the method signature will type hint in IDE's

2022-10-17 05:12 UTC, emteknetnz commented on code/Controller/AssetAdmin.php
>          return $this->getRecordUpdatedResponse($record, $form);
`getRecordUpdatedResponse()` already has them in its phpdoc

2022-10-17 05:13 UTC, emteknetnz commented on code/Controller/AssetAdmin.php
> +    public function addtocampaign(array $data, Form $form): HTTPResponse
Updated

2022-10-17 22:00 UTC, ChloeSartorelli commented on code/Controller/AssetAdmin.php
>          return $this->saveOrPublish($data, $form, true);
That's my point. `saveOrPublish()` doesn't have strong types in the method signature. Sorry, I should have more clearly indicated what method "that method" is.

2022-10-17 22:00 UTC, ChloeSartorelli commented on code/Controller/AssetAdmin.php
>          return $this->getRecordUpdatedResponse($record, $form);
Right, but it could return anything. Which means this could return anything. Which means `publish()` and `save()` might throw errors.

2022-10-17 22:00 UTC, ChloeSartorelli commented on code/Controller/AssetAdmin.php
> +        $extraData = ['message' => $results->getBody()];
For anyone looking at this in the future and wondering why this change was made, it reflects the change in https://github.com/silverstripe/silverstripe-campaign-admin/pull/244/files#diff-005db379d07dad4da0ae604f8201249c122b800056b951f9b64b05ef977b7fdcR336

2022-10-17 23:18 UTC, emteknetnz commented on code/Controller/AssetAdmin.php
>          return $this->saveOrPublish($data, $form, true);
Have added strong typing to saveOrPublish()

2022-10-17 23:21 UTC, emteknetnz commented on code/Controller/AssetAdmin.php
>          return $this->getRecordUpdatedResponse($record, $form);
For `getRecordUpdatedResponse()` I have:
- added strong typing to the `$record` param - it's already strong typed in the subsequent call to `getObjectFromData()`
- retaining dynamic typing with phpdoc for the `$form` param - it's also dynamic typed in the subsequent call to `getSchemaResponse()`

Note: `getRecordUpdatedResponse()` already had a `:HTTPResponse` strong return type

2022-10-18 00:52 UTC, GuySartorelli approved these changes
Don't merge until other PRs are ready to avoid breaking CI

2022-10-18 00:57 UTC, GuySartorelli requested changes

2022-10-18 00:57 UTC, GuySartorelli commented on code/Controller/AssetAdmin.php
> -        }
I think this needs the same treatment as https://github.com/silverstripe/silverstripe-cms/pull/2788/files#r997551623 (`isset()` would have returned false for null, so it's effectively the same check as being done in cms)

2022-10-18 05:21 UTC, emteknetnz commented on code/Controller/AssetAdmin.php
> -        }
Updated

2022-10-18 21:05 UTC, GuySartorelli approved these changes

2022-10-18 21:08 UTC, merged