API Update deprecations
silverstripe/silverstripe-asset-admin pull request #1302
Opened 2022-10-18 02:28 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-framework/issues/10531

2022-10-24 23:16 UTC, GuySartorelli requested changes
Version numbers are incorrect - use `1` major version numbering instead. This will also need to be applied to any other deprecation notices in this module.

2022-10-25 04:20 UTC, GuySartorelli requested changes

2022-10-25 04:20 UTC, GuySartorelli commented on _legacy/GraphQL/CreateFileMutationCreator.php
> + * @deprecated 1.8.0 Use _graphql directory functionality instead
The original message was more correct - the thing to use is the latest graphql, the directory is irrelevant.
The same message will need to be changed in a couple of other classes below as well.

2022-10-25 04:32 UTC, emteknetnz commented on _legacy/GraphQL/CreateFileMutationCreator.php
> + * @deprecated 1.8.0 Use _graphql directory functionality instead
Updated

2022-10-25 04:35 UTC, GuySartorelli approved these changes
MOG

2022-10-25 05:19 UTC, merged