ENH Add delete buttons for images/embeds in wysiwyg
silverstripe/silverstripe-asset-admin pull request #1331
Opened 2023-02-10 03:09 UTC by GuySartorelli

The stretch goals are shockingly non-trivial, so I'm not touching those. This PR just adds nice delete buttons when you select an image or embed (and behat tests for the selection context toolbars)

## Parent issue
- https://github.com/silverstripe/silverstripe-admin/issues/1410

2023-02-10 03:14 UTC, GuySartorelli commented on tests/behat/features/wysiwyg-embed-toolbar.feature
> +    Given a "page" "About Us" has the "Content" "[embed url="https://www.example.com/watch?v=4Eyiz8wxC8E" thumbnail="https://via.placeholder.com/200x113" class="embed" width="200" height="113"]https:
Shortcode syntax for storing the embed in the db.
Note I'm not using a real youtube or other actually embeddable URL here because I don't want this test to rely on some arbitrary resource actually existing and being accessible at the time the test is run. We don't need that for this test.

2023-02-10 03:14 UTC, GuySartorelli commented on tests/behat/src/FixtureContext.php
> +    public function iShouldSeeTheForm($not, $id, $timeout = 3)
Added the ability to check a form is _not_ present, and using this to check if the insert image modal is present.
Note that the embed modal _doesn't_ check for a form, because a form is only present in that modal if a real embed resource URL is used.

2023-02-10 03:14 UTC, GuySartorelli commented on tests/behat/src/FixtureContext.php
> +        var editor = jQuery('#$inputFieldId').entwine('ss').getEditor(),
Added indents to make this easier to read

2023-02-10 03:14 UTC, GuySartorelli commented on tests/behat/src/FixtureContext.php
> +        $inputField->getParent()->find('css', 'iframe')->click();
We have to click on the editor first to it has focus and knows this is the "active" editor, or the toolbar doesn't appear.

2023-02-10 03:15 UTC, GuySartorelli commented
js test failure is expected until https://github.com/silverstripe/silverstripe-asset-admin/pull/1330 is merged in

2023-02-10 03:58 UTC, michalkleiner commented on tests/behat/features/wysiwyg-embed-toolbar.feature
> +    Given a "page" "About Us" has the "Content" "[embed url="https://www.example.com/watch?v=4Eyiz8wxC8E" thumbnail="https://via.placeholder.com/200x113" class="embed" width="200" height="113"]https:
> Note I'm not using a real youtube or other actually embeddable URL here because I don't want this test to rely on some arbitrary resource actually existing and being accessible at the time the test is run.

But still relying on placeholder.com. I guess there's no point using a local image instead?

2023-02-10 04:46 UTC, GuySartorelli commented on tests/behat/features/wysiwyg-embed-toolbar.feature
> +    Given a "page" "About Us" has the "Content" "[embed url="https://www.example.com/watch?v=4Eyiz8wxC8E" thumbnail="https://via.placeholder.com/200x113" class="embed" width="200" height="113"]https:
Yeah that's a fair point. I didn't want to hardcode an image URL but I guess there's no harm in it - we'll always be running this test with default config presumably so the URL should be reliable. I'll (try to remember to) make that change on Monday.

2023-02-13 02:40 UTC, emteknetnz reviewed
This works good, do we need to update the behat test re placeholder.com?

**Before**
![image](https://user-images.githubusercontent.com/4809037/218358359-f84556a4-c38c-4651-8253-72c8bb772a3b.png)

**After**
![image](https://user-images.githubusercontent.com/4809037/218358385-16548dbf-5362-4b82-925c-863283df68a6.png)

2023-02-13 02:40 UTC, emteknetnz commented on tests/behat/features/wysiwyg-embed-toolbar.feature
> +    Given a "page" "About Us" has the "Content" "[embed url="https://www.example.com/watch?v=4Eyiz8wxC8E" thumbnail="https://via.placeholder.com/200x113" class="embed" width="200" height="113"]https:
Do we need to make an update here?

2023-02-13 02:41 UTC, GuySartorelli commented on tests/behat/features/wysiwyg-embed-toolbar.feature
> +    Given a "page" "About Us" has the "Content" "[embed url="https://www.example.com/watch?v=4Eyiz8wxC8E" thumbnail="https://via.placeholder.com/200x113" class="embed" width="200" height="113"]https:
Yes, sorry, I forgot to do that. Will do along with any other changes you recommend when you've finished your review

2023-02-13 02:48 UTC, emteknetnz requested changes

2023-02-13 02:48 UTC, emteknetnz commented on tests/behat/features/wysiwyg-embed-toolbar.feature
> +    Given a "page" "About Us" has the "Content" "[embed url="https://www.example.com/watch?v=4Eyiz8wxC8E" thumbnail="https://via.placeholder.com/200x113" class="embed" width="200" height="113"]https:
Just need to sort out placeholder.com (and maybe example.com)

2023-02-13 02:48 UTC, emteknetnz commented on tests/behat/features/wysiwyg-embed-toolbar.feature
> +    When I select the media "https://www.example.com/watch?v=4Eyiz8wxC8E" in the "Content" HTML field
Also here (maybe)

2023-02-13 02:48 UTC, emteknetnz commented on tests/behat/features/wysiwyg-embed-toolbar.feature
> +    Then the "Content" HTML field should not contain "https://www.example.com/watch?v=4Eyiz8wxC8E"
And here (maybe)

2023-02-13 02:50 UTC, GuySartorelli commented on tests/behat/features/wysiwyg-embed-toolbar.feature
> +    Given a "page" "About Us" has the "Content" "[embed url="https://www.example.com/watch?v=4Eyiz8wxC8E" thumbnail="https://via.placeholder.com/200x113" class="embed" width="200" height="113"]https:
example.com is okay - this is a domain that's explicitly intended to be used for example URLs and won't cause problems for us even if it suddenly becomes unavailable with the way this test is set up. Will replace the placeholder URL with some relative file.

2023-02-13 03:04 UTC, GuySartorelli commented on tests/behat/features/wysiwyg-embed-toolbar.feature
> +    Given a "page" "About Us" has the "Content" "[embed url="https://www.example.com/watch?v=4Eyiz8wxC8E" thumbnail="https://via.placeholder.com/200x113" class="embed" width="200" height="113"]https:
Done

2023-02-13 03:05 UTC, GuySartorelli commented on tests/behat/features/wysiwyg-embed-toolbar.feature
> +    Given a "page" "About Us" has the "Content" "[embed url="https://www.example.com/watch?v=4Eyiz8wxC8E" thumbnail="https://via.placeholder.com/200x113" class="embed" width="200" height="113"]https:
Done

2023-02-13 03:05 UTC, GuySartorelli commented
Rebased so js tests can pass, and resolved feedback.

2023-02-13 19:58 UTC, emteknetnz approved these changes

2023-02-13 19:59 UTC, merged