FIX Replaced deprecated React functions
silverstripe/silverstripe-asset-admin pull request #1337
Opened 2023-03-13 19:38 UTC by sabina-talipova

### Description
- Replaced deprecated React function `componentWillReceiveProps` with `componentDidUpdate`

### Parent issue
- https://github.com/silverstripe/silverstripe-admin/issues/1416

2023-03-13 20:49 UTC, sabina-talipova commented on client/src/containers/Gallery/Gallery.scss
> +    @include form-control-focus(true);
`form-control-focus` is deprecated https://github.com/twbs/bootstrap/issues/29096.
I just suppress a warning, but probably we could remove this include.

2023-03-21 01:42 UTC, maxime-rainville requested changes
Just partial review.

2023-03-21 01:42 UTC, maxime-rainville commented on client/src/components/AssetDropzone/AssetDropzone.js
> +  componentDidUpdate(prevProps) {
I'm going to assume this is related to this. When I upload multiple files all at once with this PR enabled, I get weird behaviour where the files don't appear to complete.

[Screencast from 2023-03-21 14-11-16.webm](https://user-images.githubusercontent.com/1168676/226497790-6503c9a0-a95a-4bc8-9503-70bdb2b880e8.webm)

In this video, I start out without the PR and upload a bunch of files successfully. I swap to the PR ... some files are uploaded successfully but not some others. I swap back to the 2.0 branch, and upload work again.

2023-03-21 01:42 UTC, maxime-rainville commented on client/src/components/GalleryItem/GalleryItem.js
> +    if (shouldLoadImage(this.props)) {
This seems to be working fine.

2023-03-21 01:42 UTC, maxime-rainville commented on client/src/components/InsertEmbedModal/InsertEmbedModal.js
> +      this.setOverrides(this.props);
This still seems to work fine.

2023-03-21 05:24 UTC, maxime-rainville requested changes
Completed review. Just need to fix the issue when uploading multiple files. 

I think the proper fix for the deprecated `form-control-focus`  is to include the appriate rules directly in the component.

2023-03-21 05:24 UTC, maxime-rainville commented on client/src/containers/AssetAdmin/AssetAdmin.js
> +  componentDidUpdate() {
Seems to be working fine.

2023-03-21 05:24 UTC, maxime-rainville commented on client/src/containers/Gallery/Gallery.js
> +  componentWillUnmount() {
All of this still seems to work fine.

2023-03-21 05:24 UTC, maxime-rainville commented on client/src/containers/Gallery/Gallery.scss
> +    @include form-control-focus(true);
Looking at the [matching PR on bootstrap](https://github.com/twbs/bootstrap/pull/28262/files) it looks like we could simply copy past this snippet here instead.

```scss
&:focus {
    color: $input-focus-color;
    background-color: $input-focus-bg;
    border-color: $input-focus-border-color;
    outline: 0;
    // Avoid using mixin so we can pass custom focus shadow properly
    @if $enable-shadows {
      box-shadow: $input-box-shadow, $input-focus-box-shadow;
    } @else {
      box-shadow: $input-focus-box-shadow;
    }
  }
```

2023-03-21 05:24 UTC, maxime-rainville commented on client/src/containers/Gallery/GalleryDND.js
> +  componentDidUpdate() {
Works fine.

2023-03-21 05:24 UTC, maxime-rainville commented on client/src/containers/HistoryList/HistoryList.js
> +  componentDidUpdate(prevProps) {
Didn't even know this thing existed. I've enabled it and it seems to be working.

2023-03-21 05:24 UTC, maxime-rainville commented on client/src/containers/InsertMediaModal/InsertMediaModal.js
> +  componentDidUpdate(prevProps) {
Still seems to be working fine.

2023-03-21 22:46 UTC, sabina-talipova commented on client/src/containers/Gallery/Gallery.scss
> +    @include form-control-focus(true);
DONE

2023-03-22 03:44 UTC, sabina-talipova commented on client/src/components/AssetDropzone/AssetDropzone.js
> +  componentDidUpdate(prevProps) {
I've fixed it. Problem was in another file.

2023-03-24 01:20 UTC, maxime-rainville commented on client/src/components/AssetDropzone/AssetDropzone.js
> +  componentDidUpdate(prevProps) {
Looks like it works properly now. Can you point me to what you actually did to fix it?

2023-03-24 01:21 UTC, maxime-rainville approved these changes

2023-03-24 01:23 UTC, merged