MNT Update test label
silverstripe/silverstripe-asset-admin pull request #1343
Opened 2023-03-28 06:10 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-admin/issues/1414

2023-03-28 21:54 UTC, GuySartorelli requested changes
The following still need to be updated:
- a comment in `client/src/containers/Gallery/Gallery.js` that mentions `componentWillReceiveProps`
- another test `client/src/components/UploadField/tests/UploadField-test.js` that mentions `componentWillReceiveProps`

2023-03-29 21:53 UTC, emteknetnz commented
Updated

I couldn't figure out what comment in Gallery.js referred to even after looking at the CMS 4 version so I just deleted it

2023-03-30 21:37 UTC, GuySartorelli approved these changes

2023-03-30 21:37 UTC, GuySartorelli commented
Failing tests are unrelated

2023-03-30 21:37 UTC, merged