MNT Use React Testing Library
silverstripe/silverstripe-asset-admin pull request #1355
Opened 2023-05-08 03:19 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-admin/issues/1509

2023-05-08 03:21 UTC, emteknetnz commented on client/src/components/AssetDropzone/tests/AssetDropzone-test.js
> -  describe('constructor()', () => {
Removed because it's testing internals

2023-05-08 03:43 UTC, emteknetnz commented on client/src/components/AssetDropzone/tests/AssetDropzone-test.js
> -/* global jest, describe, it, expect, beforeEach, FormData */
I simply cannot get interactions with the rendered dropzone to work

A lot of this file seemed like it was just testing the internals of the dropzone lib anyway

2023-05-08 04:19 UTC, emteknetnz commented on client/src/components/BulkActions/tests/BulkActions-test.js
> -    it('should return null if no option matches the given value', () => {
Removed this as there's no way to get it to return null without directly testing internals

2023-05-08 04:22 UTC, emteknetnz commented on client/src/components/BulkActions/tests/BulkActions-test.js
> -  describe('handleChangeValue()', () => {
There were mocking class methods which seems nonsenscial

2023-05-08 04:50 UTC, emteknetnz commented on client/src/components/GalleryItem/tests/GalleryItem-test.js
> -  describe('hasError()', () => {
These tests are covered by the onRemoveErroredUpload/onCancelUpload tests above

2023-05-08 04:57 UTC, emteknetnz commented on client/src/components/GalleryItem/tests/GalleryItem-test.js
> -    it('should stop propagation of the event', () => {
Cannot test this, it's not something that's passed as a prop or something that renders

2023-05-09 00:56 UTC, emteknetnz commented on client/src/components/ProportionConstraintField/tests/ProportionConstraintField-test.js
> -  describe('syncFields()', () => {
These are covered by the "onAutofill" tests above

2023-05-09 00:56 UTC, emteknetnz commented on client/src/components/ProportionConstraintField/tests/ProportionConstraintField-test.js
> -  describe('handlePresetSelect()', () => {
This is too hard to test as it's triggered by a deeply nested component

2023-05-09 00:57 UTC, emteknetnz commented on client/src/components/ProportionConstraintField/tests/ProportionConstraintField-test.js
> -  describe('handleBlur()', () => {
These are too hard to test as it's triggered by a deeply nested component

2023-05-09 01:00 UTC, emteknetnz commented on client/src/components/ProportionConstraintField/tests/ProportionConstraintField-test.js
> -      ['default image size preset is the first default', {}, 1234],
This is a duplicate of a test above of the testing that the default should be 1234

2023-05-09 03:24 UTC, emteknetnz commented on client/src/containers/AssetAdmin/tests/AssetAdmin-test.js
> -    it('should call handleOpenFile if action is creating a folder in admin', () => {
These tests were mocking class methods

2023-05-09 23:50 UTC, emteknetnz commented on client/src/containers/Gallery/tests/Gallery-test.js
> -  describe('getSelection()', () => {
I couldn't find a viable way to test this with RTL

2023-05-09 23:51 UTC, emteknetnz commented on client/src/containers/Gallery/tests/Gallery-test.js
> -  describe('renderSearchAlert()', () => {
getSearchMessage() doesn't appear to be used, so cannot test it as nothing is rendered using it

2023-05-10 00:00 UTC, emteknetnz commented on client/src/containers/Gallery/tests/Gallery-test.js
> -  describe('handleSetPage', () => {
This is rendered on a deeply nested component and is too hard to test

2023-05-10 00:11 UTC, emteknetnz commented on client/src/containers/Gallery/tests/Gallery-test.js
> -  describe('handleSuccessfulUpload()', () => {
This is testing on a deeply nested component

2023-05-10 00:12 UTC, emteknetnz commented on client/src/containers/Gallery/tests/Gallery-test.js
> -  describe('handleSort()', () => {
This is testing on a deeply nested component

2023-05-10 00:14 UTC, emteknetnz commented on client/src/containers/Gallery/tests/Gallery-test.js
> -    it('should not return a BulkActionsComponent if there are no selected items', () => {
This is a duplicate of`Gallery renderBulkActions() should not render bulk actions if there are no selected files`

2023-05-10 00:15 UTC, emteknetnz commented on client/src/containers/Gallery/tests/Gallery-test.js
> -    it(`should return a BulkActionsComponent if there are items in the
This is a duplicate of `Gallery renderBulkActions() should not render bulk actions if not admin type`

2023-05-10 00:16 UTC, emteknetnz commented on client/src/containers/Gallery/tests/Gallery-test.js
> -  describe('itemIsSelected()', () => {
This is testing a deeply nested component

2023-05-10 00:17 UTC, emteknetnz commented on client/src/containers/Gallery/tests/Gallery-test.js
> -  describe('handleActivate()', () => {
This is testing on a deeply nested component

2023-05-10 00:17 UTC, emteknetnz commented on client/src/containers/Gallery/tests/Gallery-test.js
> -  describe('handleSelect()', () => {
This is testing on a deeply nested component

2023-05-10 00:57 UTC, emteknetnz commented on client/src/containers/Gallery/tests/Gallery-test.js
> -  describe('renderGalleryView()', () => {
This is testing a deeply nested comonent

2023-05-10 01:46 UTC, emteknetnz commented on client/src/containers/TableView/tests/TableView-test.js
> -  describe('handleActivate()', () => {
I couldn't work out a way to test this

2023-05-10 01:46 UTC, emteknetnz commented on client/src/containers/TableView/tests/TableView-test.js
> -  describe('handleRowClick()', () => {
I couldn't work out a way to test this

2023-05-10 01:46 UTC, emteknetnz commented on client/src/containers/TableView/tests/TableView-test.js
> -  describe('handleSort()', () => {
I couldn't work out a way to test this

2023-05-10 01:46 UTC, emteknetnz commented on client/src/containers/TableView/tests/TableView-test.js
> +jest.mock('griddle-react', () => ({
Mocking griddle because it throws a large amount of errors if we try to render it

2023-05-10 02:24 UTC, emteknetnz commented on client/src/containers/ThumbnailView/tests/ThumbnailView-test.js
> -    it('should have cancel callbacks and no activate callback', () => {
This was only testing props on nested components

2023-05-10 03:53 UTC, emteknetnz commented on client/src/components/BulkActions/tests/BulkActions-test.js
> -    it('should return undefined if no valid option is selected', () => {
I couldn't work out a way to test this

2023-05-12 03:45 UTC, sabina-talipova requested changes
Additional question:
There are a lot of skipped test cases that existed before and were removed from current version. Are we planning to add them in the future? If yes, could you create ticket for this, please.

2023-05-12 03:45 UTC, sabina-talipova commented on client/src/components/BulkActions/tests/BulkActions-test.js
> +  await promise;
What do we test in this test case? Doe we have any expected result?

2023-05-12 03:45 UTC, sabina-talipova commented on client/src/components/BulkActions/tests/BulkActions-test.js
> +test('BulkActions canApply() shows an action button when canApply returns true', () => {
```suggestion
test('BulkActions canApply() shows an action button when canApply returns false', () => {
```

2023-05-12 03:45 UTC, sabina-talipova commented on client/src/components/BulkActions/tests/BulkActions-test.js
> +test('BulkActions getOptionsByValue() should return the option which matches the given value', async () => {
Does this test replace all previous tests, like `'should use callback if no confirm callback is configured'` for example?

2023-05-12 03:45 UTC, sabina-talipova commented on client/src/components/GalleryToolbar/Buttons/tests/AddFolderButton-test.js
> +  fireEvent.click(button);
```suggestion
  fireEvent.click(button);
  expect(onCreateFolder).toHaveBeenCalled();
```

2023-05-12 03:45 UTC, sabina-talipova commented on client/src/containers/BulkDeleteConfirmation/tests/BulkDeleteMessage-test.js
> +  expect(container.querySelector('p').textContent).toBe(getMessage('1'));
Should we check length of children as before?
`expect(container.children.length).toEqual(2);`

2023-05-12 03:45 UTC, sabina-talipova commented on client/src/containers/BulkDeleteConfirmation/tests/BulkDeleteMessage-test.js
> +  expect(container.querySelector('p').textContent).toBe(getMessage('5'));
Should we check length of children as before?
`expect(container.children.length).toEqual(2);`

2023-05-12 03:45 UTC, sabina-talipova commented on client/src/containers/BulkDeleteConfirmation/tests/BulkDeleteMessage-test.js
> +  expect(container.querySelector('p').textContent).toBe(getMessage('6'));
Should we check length of children as before?
`expect(container.children.length).toEqual(2);`

2023-05-12 03:45 UTC, sabina-talipova commented on client/src/containers/BulkDeleteConfirmation/tests/BulkDeleteMessage-test.js
> +  expect(container.querySelector('p').textContent).toBe(getMessage('5'));
Should we check length of children as before?
`expect(container.children.length).toEqual(2);`

2023-05-12 03:45 UTC, sabina-talipova commented on client/src/containers/BulkDeleteConfirmation/tests/BulkDeleteMessage-test.js
> +  expect(container.querySelector('p').textContent).toBe(getMessage('10'));
Should we check length of children as before?
`expect(container.children.length).toEqual(2);`

2023-05-12 03:45 UTC, sabina-talipova commented on client/src/containers/BulkDeleteConfirmation/tests/BulkDeleteMessage-test.js
> +  expect(container.querySelector('p').textContent).toBe(emptyFolderMessage);
Should we check length of children as before?
`expect(container.children.length).toEqual(2);`

2023-05-12 03:45 UTC, sabina-talipova commented on client/src/containers/BulkDeleteConfirmation/tests/BulkDeleteMessage-test.js
> +  expect(container.querySelector('p').textContent).toBe(getMessage('1'));
Could we check both messages?

2023-05-12 03:45 UTC, sabina-talipova commented on client/src/containers/BulkDeleteConfirmation/tests/BulkDeleteMessage-test.js
> +  expect(container.querySelector('p').textContent).toBe(getMessage('2'));
Could we check both messages?

2023-05-12 03:45 UTC, sabina-talipova commented on client/src/containers/TableView/tests/TableView-test.js
Are we planning to recreate all skipped(removed) test cases with RTL in the future? Could you, please, create ticket for this. Thank you.

2023-05-12 03:45 UTC, sabina-talipova requested changes
Additional question:
There are a lot of skipped test cases that existed before and were removed from current version. Are we planning to add them in the future? If yes, could you create ticket for this, please.

2023-05-15 00:01 UTC, emteknetnz commented on client/src/components/BulkActions/tests/BulkActions-test.js
> +test('BulkActions canApply() shows an action button when canApply returns true', () => {
Updated

2023-05-15 00:03 UTC, emteknetnz commented on client/src/components/BulkActions/tests/BulkActions-test.js
> +test('BulkActions getOptionsByValue() should return the option which matches the given value', async () => {
No, it replaces the previous test `it('should return the option which matches the given value')`

2023-05-15 00:06 UTC, emteknetnz commented on client/src/components/BulkActions/tests/BulkActions-test.js
> +  await promise;
Updated

2023-05-15 00:07 UTC, emteknetnz commented on client/src/components/GalleryToolbar/Buttons/tests/AddFolderButton-test.js
> +  fireEvent.click(button);
Updated

2023-05-15 00:10 UTC, emteknetnz commented on client/src/containers/BulkDeleteConfirmation/tests/BulkDeleteMessage-test.js
> +  expect(container.querySelector('p').textContent).toBe(getMessage('1'));
I don't think so, while it makes sense to assert the length of things like the number of buttons rendered, it doesn't make sense to assert the number of general DOM elements rendered

2023-05-15 00:10 UTC, emteknetnz commented on client/src/containers/BulkDeleteConfirmation/tests/BulkDeleteMessage-test.js
> +  expect(container.querySelector('p').textContent).toBe(getMessage('5'));
As above, I don't think so

2023-05-15 00:11 UTC, emteknetnz commented on client/src/containers/BulkDeleteConfirmation/tests/BulkDeleteMessage-test.js
> +  expect(container.querySelector('p').textContent).toBe(getMessage('5'));
As above, I don't think so

2023-05-15 00:11 UTC, emteknetnz commented on client/src/containers/BulkDeleteConfirmation/tests/BulkDeleteMessage-test.js
> +  expect(container.querySelector('p').textContent).toBe(getMessage('10'));
As above, I don't think so

2023-05-15 00:21 UTC, emteknetnz commented on client/src/containers/BulkDeleteConfirmation/tests/BulkDeleteMessage-test.js
> +  expect(container.querySelector('p').textContent).toBe(emptyFolderMessage);
As above, I don't think so

2023-05-15 00:23 UTC, emteknetnz commented on client/src/containers/BulkDeleteConfirmation/tests/BulkDeleteMessage-test.js
> +  expect(container.querySelector('p').textContent).toBe(getMessage('2'));
I'm not sure what you mean by both messages? There's only one message?

2023-05-15 00:23 UTC, emteknetnz commented on client/src/containers/BulkDeleteConfirmation/tests/BulkDeleteMessage-test.js
> +  expect(container.querySelector('p').textContent).toBe(getMessage('1'));
I'm not sure what you mean by both messages? There's only one message?

2023-05-15 00:24 UTC, emteknetnz commented on client/src/containers/TableView/tests/TableView-test.js
Not planning to

2023-05-15 00:27 UTC, emteknetnz commented on client/src/containers/BulkDeleteConfirmation/tests/BulkDeleteMessage-test.js
> +  expect(container.querySelector('p').textContent).toBe(getMessage('6'));
As above, I don't think so

2023-05-15 00:29 UTC, emteknetnz commented
> There are a lot of skipped test cases that existed before and were removed from current version. Are we planning to add them in the future? If yes, could you create ticket for this, please.

Not planning to

2023-05-15 01:21 UTC, sabina-talipova commented on client/src/containers/BulkDeleteConfirmation/tests/BulkDeleteMessage-test.js
> +  expect(container.querySelector('p').textContent).toBe(getMessage('1'));
Not sure how important this is, but in the previous version of this test, we also checked that the `children` has two paragraphs, one with `expectedMessage`, the other with `unlinkFileWarning`.

2023-05-15 01:21 UTC, sabina-talipova commented on client/src/containers/BulkDeleteConfirmation/tests/BulkDeleteMessage-test.js
> +  expect(container.querySelector('p').textContent).toBe(getMessage('2'));
Not sure how important this is, but in the previous version of this test, we also checked that the `children` has two paragraphs, one with `expectedMessage`, the other with `unlinkFileWarning`.

2023-05-15 01:21 UTC, sabina-talipova commented on client/src/containers/BulkDeleteConfirmation/tests/BulkDeleteMessage-test.js
> +  expect(container.querySelector('p').textContent).toBe(getMessage('1'));
As I see in the previous version of this test, we also checked that the child has two paragraphs, one with a `message`, the other with `unlinkFileWarning`.
If you think that this is not important, no worries, we can skip them.

2023-05-15 01:21 UTC, sabina-talipova commented on client/src/containers/BulkDeleteConfirmation/tests/BulkDeleteMessage-test.js
> +  expect(container.querySelector('p').textContent).toBe(getMessage('5'));
See comment above.

2023-05-15 01:21 UTC, sabina-talipova commented on client/src/containers/BulkDeleteConfirmation/tests/BulkDeleteMessage-test.js
> +  expect(container.querySelector('p').textContent).toBe(getMessage('6'));
See comment above.

2023-05-15 01:21 UTC, sabina-talipova commented on client/src/containers/BulkDeleteConfirmation/tests/BulkDeleteMessage-test.js
> +  expect(container.querySelector('p').textContent).toBe(getMessage('5'));
See comment above.

2023-05-15 01:21 UTC, sabina-talipova commented on client/src/containers/BulkDeleteConfirmation/tests/BulkDeleteMessage-test.js
> +  expect(container.querySelector('p').textContent).toBe(getMessage('10'));
See comment above.

2023-05-15 01:21 UTC, sabina-talipova commented on client/src/containers/BulkDeleteConfirmation/tests/BulkDeleteMessage-test.js
> +  expect(container.querySelector('p').textContent).toBe(emptyFolderMessage);
See comment above.

2023-05-15 01:21 UTC, sabina-talipova commented on client/src/components/BulkActions/tests/BulkActions-test.js
> +test('BulkActions getOptionsByValue() should return the option which matches the given value', async () => {
Why did you skip test cases for `handleChangeValue()` ?

2023-05-15 05:40 UTC, emteknetnz commented on client/src/components/BulkActions/tests/BulkActions-test.js
> +test('BulkActions getOptionsByValue() should return the option which matches the given value', async () => {
When I did the PR I left a comment - "There (These) were mocking class methods which seems nonsenscial"
i.e.
```
      bulkActions.getOptionByValue = jest.fn();
      bulkActions.applyAction = jest.fn();
```
There isn't any sensible way to translate this to RTL

2023-05-15 05:40 UTC, emteknetnz commented on client/src/containers/BulkDeleteConfirmation/tests/BulkDeleteMessage-test.js
> +  expect(container.querySelector('p').textContent).toBe(getMessage('1'));
It's not important, let's skip them

2023-05-15 05:41 UTC, emteknetnz commented on client/src/containers/BulkDeleteConfirmation/tests/BulkDeleteMessage-test.js
> +  expect(container.querySelector('p').textContent).toBe(getMessage('5'));
See comment above

2023-05-15 05:41 UTC, emteknetnz commented on client/src/containers/BulkDeleteConfirmation/tests/BulkDeleteMessage-test.js
> +  expect(container.querySelector('p').textContent).toBe(getMessage('6'));
See comment above

2023-05-15 05:41 UTC, emteknetnz commented on client/src/containers/BulkDeleteConfirmation/tests/BulkDeleteMessage-test.js
> +  expect(container.querySelector('p').textContent).toBe(getMessage('5'));
See comment above

2023-05-15 05:41 UTC, emteknetnz commented on client/src/containers/BulkDeleteConfirmation/tests/BulkDeleteMessage-test.js
> +  expect(container.querySelector('p').textContent).toBe(getMessage('10'));
See comment above

2023-05-15 05:41 UTC, emteknetnz commented on client/src/containers/BulkDeleteConfirmation/tests/BulkDeleteMessage-test.js
> +  expect(container.querySelector('p').textContent).toBe(emptyFolderMessage);
See comment above

2023-05-15 05:47 UTC, emteknetnz commented on client/src/containers/BulkDeleteConfirmation/tests/BulkDeleteMessage-test.js
> +  expect(container.querySelector('p').textContent).toBe(getMessage('1'));
Updated - now we test for both messages

2023-05-15 05:47 UTC, emteknetnz commented on client/src/containers/BulkDeleteConfirmation/tests/BulkDeleteMessage-test.js
> +  expect(container.querySelector('p').textContent).toBe(getMessage('2'));
Updated

2023-05-15 07:31 UTC, sabina-talipova approved these changes
LGTM

2023-05-15 07:31 UTC, merged