FIX ESLint issues
silverstripe/silverstripe-asset-admin pull request #1371
Opened 2023-06-28 02:11 UTC by sabina-talipova

## Description
Turn on some of the ESLint.
## Parent issue
-  https://github.com/silverstripe/silverstripe-admin/issues/1433

2023-07-05 04:47 UTC, emteknetnz requested changes

2023-07-05 04:47 UTC, emteknetnz commented on client/src/components/GalleryItem/tests/SelectGalleryItemTracker.js
> +    this.setState((prevState) => ({ selected: !prevState.selected }));
Is this sort of change required to get linting to pass? Otherwise I'd prefer to not have any actual code changes.

2023-07-05 04:48 UTC, emteknetnz requested changes
.

2023-07-06 01:41 UTC, sabina-talipova commented on client/src/components/GalleryItem/tests/SelectGalleryItemTracker.js
> +    this.setState((prevState) => ({ selected: !prevState.selected }));
This is the rule [react/no-access-state-in-setstate](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/no-access-state-in-setstate.md).
```txt
Usage of this.state inside setState calls might result
in errors when two state calls are called in batch and thus referencing 
old state and not the current state.
``` 
This problem describes [there](https://legacy.reactjs.org/docs/react-component.html#setstate)
```txt
setState() does not always immediately update the component.
It may batch or defer the update until later. This makes reading this.state right after
calling setState() a potential pitfall. Instead, use componentDidUpdate or a setState callback
(setState(updater, callback)), either of which are guaranteed to fire after the update has been applied. 
If you need to set the state based on the previous state, read about the updater argument below.
```

2023-07-06 23:50 UTC, emteknetnz approved these changes

2023-07-06 23:50 UTC, merged