MNT Behat test to test special characters in shortcode
silverstripe/silverstripe-asset-admin pull request #1376
Opened 2023-08-07 22:22 UTC by sabina-talipova

## Parent issue
- https://github.com/silverstripe/silverstripe-framework/issues/10451

2023-08-07 23:07 UTC, sabina-talipova commented
Require [PR](https://github.com/silverstripe/silverstripe-assets/pull/565)

2023-08-08 01:49 UTC, GuySartorelli commented
I've rerun the behat tests but they're failing. Have confirmed that behat is running against the recent changes, so there's either something wrong with the test or the new logic.

2023-08-08 03:12 UTC, sabina-talipova commented
Fixed

2023-08-08 04:43 UTC, GuySartorelli requested changes
It looks like this still isn't working as expected.

I would expect to see `My alt updated &amp; saved` in the HTML, but this test shows `My alt updated & saved` which is incorrect.

We should also add to the behat test what happens on the front-end, to validate that the frontend markup has `alt="My alt updated &amp; saved"` and not `alt="My alt updated & saved"` or `alt="My alt updated &amp;amp; saved"`.

2023-08-08 23:10 UTC, sabina-talipova commented
Follow [TinyMC documentation] (https://www.tiny.cloud/docs/tinymce/6/content-filtering/#entities)  and [this](https://www.tiny.cloud/docs/tinymce/6/content-filtering/#entity_encoding):

>  The base entities <, >, &, ', and " will always be entity encoded into their named equivalents.

So my assumption, when we just start to work on content and add new special characters TinyMC will always encoded them into their named equivalents. So this we see this here.
**First string that I get before "Save" (named equivalents):**
```js
document.querySelector('textarea[name="Content"]').value
'<div class="captionImage leftAlone" style="width: 444px;">[image src="http://localhost:90/sink413x/assets/Uploads/GitHub-avatar-v2.jpeg" id="3" width="444" height="444" class="leftAlone ss-htmleditorfield-file image" alt="Batman &amp; Robin"]\n<p class="caption leftAlone">Batman &amp; Robin</p>\n</div>'
```
**Second string that I get after "Save" (entities):**
```js
document.querySelector('textarea[name="Content"]').value
'<div class="captionImage leftAlone" style="width: 444px;">[image src="/sink413x/assets/Uploads/GitHub-avatar-v2.jpeg" id="3" width="444" height="444" class="leftAlone ss-htmleditorfield-file image" alt="Batman & Robin"]\n<p class="caption leftAlone">Batman & Robin</p>\n</div>'
```

**Third string that I get after I made some changes, but not "Save" yet (named equivalents):** 
```js
document.querySelector('textarea[name="Content"]').value
'<div class="captionImage leftAlone" style="width: 444px;">[image src="/sink413x/assets/Uploads/GitHub-avatar-v2.jpeg" id="3" width="444" height="444" class="leftAlone ss-htmleditorfield-file image" alt="Batman &amp; Robin"]\n<p class="caption leftAlone">Batman &amp; Robin &amp; Co</p>\n</div>'
```
This string we pass to the server from the client :
```txt
<div class="captionImage leftAlone" style="width: 444px;">[image src="/sink413x/assets/Uploads/GitHub-avatar-v2.jpeg" id="3" width="444" height="444" class="leftAlone ss-htmleditorfield-file image" alt="Batman &amp; Robin"]
<p class="caption leftAlone">Batman &amp; Robin &amp; Co</p>
</div>
```
This string we store in DB:
```txt
<div class="captionImage leftAlone" style="width: 444px;">[image src="/sink413x/assets/Uploads/GitHub-avatar-v2.jpeg" id="3" width="444" height="444" class="leftAlone ss-htmleditorfield-file image" alt="Batman &amp; Robin"]
<p class="caption leftAlone">Batman &amp; Robin &amp; Co</p>
```
It looks like TinyMC convert html entities into named equivalents in whole content every time when we edit it. When we return `&` as is from DB (I updated `&amp;` with `&` in string in DB), then TinyMC shows it as is, but encode it to `&amp;` as soon as we make any small changes (add 'Space'). 

So for behat test we should expect that after "Save" we will get `My alt updated & saved` instead of `My alt updated &amp; saved`. I add some test to show all this explanation above.

2023-08-09 21:51 UTC, GuySartorelli requested changes

2023-08-09 21:51 UTC, GuySartorelli commented on tests/behat/features/insert-an-image.feature
> +      And the "Content" HTML field should contain "My caption updated &amp; saved"
This doesn't seem right - when we click "update file", we should see the same thing we filled in, i.e. the unchanged `My title text updated & saved` value.
Looks like we still have a little bit of work left to do here in the implementation.

2023-08-09 21:51 UTC, GuySartorelli commented on tests/behat/features/insert-an-image.feature
> +      And I should see an "img[title='My title text updated &amp; saved']" element
It may not seem like it, but this actually means we're _still double encoding_. These should be queryable as `img[alt='My alt updated & saved']` and `img[title='My title text updated & saved']`

I've gone back and re-run my manual tests. It turns out that the inspector in both firefox and chrome shows the decoded version of the string. So I saw this:
![Screenshot from 2023-08-10 09-48-40](https://github.com/silverstripe/silverstripe-asset-admin/assets/36352093/102d0506-e3a7-4555-9ce8-35125d104b5f)
`alt="some &amp; thing"`

But the actual value (seen by right clicking and selecting "Edit as HTML") was this:
![Screenshot from 2023-08-10 09-48-52](https://github.com/silverstripe/silverstripe-asset-admin/assets/36352093/12dee335-ef07-4525-9ad1-c49d598bc8f4)
`alt="some &amp;amp; thing"`

So we're still double encoding. Sorry I didn't catch it before merging the changes.

2023-08-09 22:27 UTC, sabina-talipova commented on tests/behat/features/insert-an-image.feature
> +      And I should see an "img[title='My title text updated &amp; saved']" element
All changes that were made are correct, but they fixed problem in CMS itself. Current problem happens now when we display Content on a page.

2023-08-09 22:28 UTC, sabina-talipova commented on tests/behat/features/insert-an-image.feature
> +      And I should see an "img[title='My title text updated &amp; saved']" element
I'll fix it and update Behat tests.

2023-08-10 02:46 UTC, sabina-talipova commented on tests/behat/features/insert-an-image.feature
> +      And I should see an "img[title='My title text updated &amp; saved']" element
Could you, please review [this PR](https://github.com/silverstripe/silverstripe-assets/pull/567)

2023-08-10 03:26 UTC, sabina-talipova commented
Tests require [this PR](https://github.com/silverstripe/silverstripe-assets/pull/567)

2023-08-14 00:25 UTC, GuySartorelli approved these changes
Looks good - it's green now the changes are merged.

2023-08-14 00:25 UTC, merged