MNT Fix js lint errors
silverstripe/silverstripe-asset-admin pull request #1388
Opened 2023-08-22 03:24 UTC by emteknetnz

Issue 

I did a merge-up from 2.0 => 2 though there were some `yarn lint` failures which I choose to ignore for the sake of completing the merge-up without having to commit changes without a PR.  I've fixed the `yarn lint` errors in this PR

The `yarn lint` errors were

```
vendor/silverstripe/asset-admin/client/src/containers/AssetAdmin/AssetAdmin.js
  686:13  error  'archiveFiles' is assigned a value but never used  no-unused-vars

vendor/silverstripe/asset-admin/client/src/containers/BulkDeleteConfirmation/BulkDeleteMessage.js
  78:5  error  Prefer fragment shorthand over React.Fragment  react/jsx-fragments

vendor/silverstripe/asset-admin/client/src/containers/BulkDeleteConfirmation/DeletionModal.js
  22:1  error  Expected indentation of 8 spaces but found 10  indent
```

2023-08-22 22:33 UTC, GuySartorelli commented
> there is a broken behat test on this which will be an existing failure

Is there a PR to fix that?

2023-08-22 22:34 UTC, GuySartorelli requested changes

2023-08-22 22:34 UTC, GuySartorelli commented on client/src/containers/BulkDeleteConfirmation/BulkDeleteMessage.js
> +    </>
Also remove it from the import statements.

2023-08-22 23:26 UTC, emteknetnz commented on client/src/containers/BulkDeleteConfirmation/BulkDeleteMessage.js
> +    </>
Updated

2023-08-22 23:26 UTC, emteknetnz commented on client/src/containers/BulkDeleteConfirmation/BulkDeleteMessage.js
> +    </>
> Is there a PR to fix that?

Not yet

2023-08-23 03:32 UTC, GuySartorelli approved these changes
Looks good. I was going to merge up and rerun the behat tests but the auto-merger will fail because of the linting issues and I can't be bothered merging up manually for unrelated behat failures. So, good to go.

2023-08-23 03:32 UTC, merged