FIX Image tag is converted to shortcode even if it doesn't have parent node
silverstripe/silverstripe-asset-admin pull request #1395
Opened 2023-09-06 00:02 UTC by sabina-talipova

## Description
HTML Editor Content is wrapped into `div` tag before additional processing. After processing function returns content without wrapper.

## Parent issue
-

2023-09-06 05:58 UTC, emteknetnz requested changes
Tested locally, works good

Will just need to update inline comment that mentions outerHTML

2023-09-06 05:58 UTC, emteknetnz commented on client/src/entwine/TinyMCE_ssmedia.js
> +          if (this.innerHTML !== undefined) {
There's a comment above this "Insert outerHTML in order to retain all nodes incl. <script>" - will need to update that

2023-09-06 07:41 UTC, sabina-talipova commented on client/src/entwine/TinyMCE_ssmedia.js
> +          if (this.innerHTML !== undefined) {
I've done some tests with `<script>` tag and it looks like it works, since now we have additional `div` wrapper.

2023-09-06 21:57 UTC, emteknetnz requested changes

2023-09-06 21:57 UTC, emteknetnz commented on client/src/entwine/TinyMCE_ssmedia.js
> +          if (this.innerHTML !== undefined) {
Sorry I mean update the inline comment on line 105 and just change `outerHTML` to `innerHTML` since that's what we're using now

2023-09-06 22:39 UTC, sabina-talipova commented on client/src/entwine/TinyMCE_ssmedia.js
> +          if (this.innerHTML !== undefined) {
Updated

2023-09-07 01:23 UTC, emteknetnz approved these changes

2023-09-07 01:24 UTC, merged