ENH Use SearchableMultiDropdownField
silverstripe/silverstripe-asset-admin pull request #1424
Opened 2023-11-27 02:41 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-admin/issues/1618

2023-12-11 22:01 UTC, GuySartorelli requested changes
LGTM, but needs a dependency bump for admin and framework.

2023-12-12 21:40 UTC, emteknetnz commented
Have updated composer.json

2023-12-13 00:47 UTC, GuySartorelli requested changes

2023-12-13 00:47 UTC, GuySartorelli commented on composer.json
> +        "silverstripe/cms": "^5.2",
```suggestion
        "silverstripe/cms": "^5",
```
Update the framework and admin dependencies in `require`, not cms in `require-dev`

2023-12-13 01:16 UTC, emteknetnz commented on composer.json
> +        "silverstripe/cms": "^5.2",
Opps :-) Have updated

2023-12-13 20:54 UTC, GuySartorelli approved these changes
LGTM, will merge once admin and framework PRs are merged

2023-12-14 20:33 UTC, merged