ENH Remove unused legacy graphql code
silverstripe/silverstripe-asset-admin pull request #1474
Opened 2024-06-18 07:15 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-graphql/issues/384

2024-06-20 03:54 UTC, GuySartorelli requested changes

2024-06-20 03:54 UTC, GuySartorelli commented on client/src/boot/registerQueries.js
> -import readFilesQueryLegacy from 'state/files/_legacy/readFilesQuery';
Need to remove `client/src/state/files/_legacy/` dir as well

2024-06-20 05:06 UTC, emteknetnz commented on client/src/boot/registerQueries.js
> -import readFilesQueryLegacy from 'state/files/_legacy/readFilesQuery';
Done

2024-06-21 03:00 UTC, GuySartorelli approved these changes
LGTM

2024-06-21 03:00 UTC, merged