ENH Remove animation for thumbnails by default.
silverstripe/silverstripe-asset-admin pull request #1475
Opened 2024-07-11 01:56 UTC by GuySartorelli

Needs https://github.com/silverstripe/silverstripe-assets/pull/621 to work.

## Issue
- https://github.com/silverstripe/silverstripe-assets/issues/619

2024-07-11 01:58 UTC, GuySartorelli commented on code/Model/ThumbnailGenerator.php
> +        if (!$this->getAllowsAnimation() && $file->getIsAnimated() && ClassInfo::hasMethod($file, 'RemoveAnimation')) {
Note it doesn't make sense to add the `RemoveAnimation` method to `AssetContainer` interface, because it's about image manipulation.
Even though that interface is only used by `DBFile` and `File` which both use the `ImageManipulation` trait, we shouldn't assume the object has this method for the sake of strict correctness. (even though below we assume it has whatever `$method` is lol)

2024-07-15 04:59 UTC, emteknetnz requested changes
There might be some future issue with copyright with that sample image provided, swap it to something more "sample image" like

2024-07-17 22:34 UTC, GuySartorelli commented
Swapped sample gif to one we explicitly own

2024-07-21 23:56 UTC, GuySartorelli commented on code/Model/ThumbnailGenerator.php
> +        }
See https://github.com/silverstripe/silverstripe-asset-admin/pull/1475#discussion_r1673291221 - this is now more complex logic, but that principle remains that we should adhere to the API of the `AssetContainer` interface. As such I've provided two ways to do this - one where there's an `Image_Backend` available and one where that's not available but `RemoveAnimation()` is.

2024-07-23 04:25 UTC, emteknetnz approved these changes

2024-07-23 04:26 UTC, merged