API Standardise endpoints
silverstripe/silverstripe-asset-admin pull request #1477
Opened 2024-07-22 05:01 UTC by emteknetnz

Issue https://github.com/silverstripe/.github/issues/286

2024-07-23 07:05 UTC, emteknetnz commented on client/src/containers/AssetAdmin/AssetAdmin.js
> -          }
I've removed the functionality above where if some but not all of the files were delete/archived, then show a message.

There's a few reasons why:
- I'd like the non-read endpoints to simply return a 204 (no content) on success, and a 4** code without a message on failure.  As much as possible I'd like to not return "custom success/failure messages" as that's not moving towards standard endpoints. Instead we should rely on standard HTTP status codes as much as possible.
- There are now plenty of ways to trigger 4** status codes before any files are actually deleted e.g. validating ids passed are on files that exist, canDelete() checks on all files, etc. Passing those checked and then failing to delete the file seems very unlikely. 
- If something like a 500 was returned due to an exception being thrown in PHP, the deleted JS code wouldn't have triggered anyway (would use a .catch() block for that as we're using lib/Backend)

2024-08-20 02:00 UTC, GuySartorelli requested changes

2024-08-20 02:00 UTC, ChloeSartorelli commented on _config/config.yml
> +      ThumbnailGenerator: '%$SilverStripe\AssetAdmin\Model\ThumbnailGenerator.assetadmin'
I assume this is to replace `SilverStripe\AssetAdmin\Model\ThumbnailGenerator.graphql`

Why doesn't it have `Generates: false`? That was there to prevent trying to generate new thumbnails when loading asset admin if the thumbnail generation criteria change, because that would massively slow down the CMS.

2024-08-20 02:00 UTC, ChloeSartorelli commented on _config/config.yml
> +      ThumbnailGenerator: '%$SilverStripe\AssetAdmin\Model\ThumbnailGenerator.assetadmin'
In the current CMS 5 implementation, we have the two thumbnail generators:
- `SilverStripe\AssetAdmin\Model\ThumbnailGenerator.assetadmin` is used for upload fields despite its name. It generates thumbnails because there aren't expected to be many loaded on any given page load.
- `SilverStripe\AssetAdmin\Model\ThumbnailGenerator.graphql` is used for asset admin. It doesn't generate thumbnails (other than on upload) because we expect lots of images on any given page load.

2024-08-20 02:00 UTC, ChloeSartorelli commented on client/src/components/UploadField/UploadField.js
> -    }),
Add new `endpoints` object in its place, even if its type is just `PropTypes.object`

2024-08-20 02:00 UTC, ChloeSartorelli commented on client/src/containers/AssetAdmin/AssetAdmin.js
Why are we doing `refetchFolder` a lot now, when we weren't before?

2024-08-20 02:00 UTC, ChloeSartorelli commented on client/src/containers/AssetAdmin/AssetAdmin.js
> +        return response;
Why have the conditions changed here? It's probably super obvious with the full context of how everything is put together but I haven't got that context fully.

2024-08-20 02:00 UTC, ChloeSartorelli commented on client/src/containers/AssetAdmin/AssetAdmin.js
> +    return backend.post(url, {
Some endpoints have an explicit `.method` - I haven't gotten as far as looking at the PHP than handles that yet but just philosophically, should we always have a `.method` that we dynamically respect in js?
If not, why *do* some of them have a `.method` that needs to be respected like that?

2024-08-20 02:00 UTC, ChloeSartorelli commented on client/src/containers/AssetAdmin/AssetAdmin.js
> -          }
Excellent reasoning, thank you for explaining

2024-08-20 02:00 UTC, ChloeSartorelli commented on client/src/containers/AssetAdmin/AssetAdmin.js
> +    }
Should probably add this to all of them if we're adding it to any.

2024-08-20 02:00 UTC, ChloeSartorelli commented on client/src/containers/AssetAdmin/AssetAdmin.js
> +    // return <h1>{ JSON.stringify(this.state.folder) }</h1>;
I assume this was debug code?
```suggestion
```

2024-08-20 02:00 UTC, ChloeSartorelli commented on client/src/containers/AssetAdmin/AssetAdmin.js
> +    }
What scenario does this happen in? This wasn't here before, why do we need it now?

2024-08-20 02:00 UTC, ChloeSartorelli commented on client/src/containers/AssetAdmin/AssetAdmin.js
> +          {folder && <AssetAdminBreadcrumb {...breadcrumbProps} />}
Why do we now need this condition?

2024-08-20 02:00 UTC, ChloeSartorelli commented on client/src/containers/AssetAdmin/AssetAdmin.js
> -  graphQLErrors: PropTypes.arrayOf(PropTypes.string),
I think you removed other things too? Like `folder` looks like it's in state now? Please make sure to update the propTypes.

This goes for _all_ components in _all_ PRs.

2024-08-20 02:00 UTC, ChloeSartorelli commented on client/src/containers/AssetAdmin/AssetAdmin.js
> -  withApollo
Love to see this

2024-08-20 02:00 UTC, ChloeSartorelli commented on client/src/containers/BulkDeleteConfirmation/BulkDeleteConfirmation.js
> - */
If it doesn't do that, what _does_ it do? Please update the comment instead of deleting it.

2024-08-20 02:00 UTC, ChloeSartorelli commented on code/Controller/AssetAdmin.php
> +            /* @var Folder&AssetAdminFile $file */
```suggestion
            /* @var File&AssetAdminFile $file */
```
At this point we don't know it's a folder, hence the `is_a()` check later on.

2024-08-20 02:00 UTC, ChloeSartorelli commented on code/Controller/AssetAdmin.php
> +        /* @var Folder&AssetAdminFile $file */
```suggestion
        /* @var File&AssetAdminFile $file */
```
Given the variable is named `$file` I assume we don't know this is a folder.

2024-08-20 02:00 UTC, ChloeSartorelli commented on client/src/containers/BulkDeleteConfirmation/BulkDeleteConfirmation.js
> - * This avoid firing off a GraphQL query for nothing.
Does it avoid firing off an XHR request for nothing?
If so just update instead of remove the comment. If not, are we introducing a regression?

2024-08-20 02:00 UTC, ChloeSartorelli commented on client/src/containers/Editor/Editor.js
> +  }
Probably the same reason as above (if so just link to response) - but why are we refetching data that we weren't before?

2024-08-20 02:00 UTC, ChloeSartorelli commented on client/src/containers/Editor/Editor.js
> -    const { file } = this.props;
We're still passing the file in... is that because this is still relevant (just for xhr instead of graphql)? If so, please keep the comment and just update it to match.

If that's not why we're passing file through now, why _are_ we still passing it through?

2024-08-20 02:00 UTC, ChloeSartorelli commented on client/src/containers/Editor/Editor.js
> +  // file: fileShape,
Don't keep commented-out code

2024-08-20 02:00 UTC, ChloeSartorelli commented on client/src/containers/Gallery/Gallery.js
> -              ))}
Does `errorMessage` contain the errors from the controller which used to be in `graphQLErrors`? If not, what happens with errors now?

2024-08-20 02:00 UTC, ChloeSartorelli commented on code/Controller/AssetAdmin.php
> +    private static $allowed_actions = array(
```suggestion
    private static array $allowed_actions = [
```

2024-08-20 02:00 UTC, ChloeSartorelli commented on code/Controller/AssetAdmin.php
> +    );
```suggestion
    ];
```

2024-08-20 02:00 UTC, ChloeSartorelli commented on code/Controller/AssetAdminOpen.php
> +    protected $thumbnailGenerator;
```suggestion
    protected ThumbnailGenerator $thumbnailGenerator;
```

2024-08-20 02:00 UTC, ChloeSartorelli commented on code/Controller/AssetAdminOpen.php
> +    private static $ignore_menuitem = true;
```suggestion
    private static bool $required_permission_codes = false;

    /**
     * Do not show this controller in the CMS menu
     */
    private static bool $ignore_menuitem = true;
```

2024-08-20 02:00 UTC, ChloeSartorelli commented on code/Controller/AssetAdminOpen.php
> +    // }
```suggestion
```

2024-08-20 02:00 UTC, ChloeSartorelli commented on code/Controller/AssetAdminOpen.php
> +    private static $required_permission_codes = false;
I assume you've validated that unauthenticated users can't use the `api/read` endpoint to read files?

2024-08-20 02:00 UTC, ChloeSartorelli commented on code/Controller/AssetAdminOpen.php
> +                    'url' => Controller::join_links($baseLink, 'api/read'),
```suggestion
                    'url' => $this->Link('api/read'),
```

2024-08-20 02:00 UTC, ChloeSartorelli commented on code/Controller/AssetAdminOpen.php
> +            $this->jsonError(404);
```suggestion
            $this->jsonError(400);
```
If the ID isn't an integer, the client has sent a bad request.

2024-08-20 02:00 UTC, ChloeSartorelli commented on code/Controller/AssetAdminOpen.php
> +            $data['children'] = $tmp['children'];
Why are we creating a new folder in the "Read" API?

2024-08-20 02:00 UTC, ChloeSartorelli commented on code/Controller/AssetAdminOpen.php
> +        }
We should probably follow the pattern that's used elsewhere in the CMS, where either
1. `new` is used to indicate we're creating a new record (gridfield does it this way, so that makes it the pattern for literally all admins other than CMSMain), or
2. There is no ID value passed, and we know because of the context of the request that we're creating a new item (CMSMain does it this way)

Using an ID of `0` means if the JS breaks somehow and ends up passing through a falsy value of any sort because maybe it can't read the ID or something, we'll end up creating a new item.

That is assuming that's what the `0` is used for, if it's for something else please make it clear in the comment what it's actually used for.

2024-08-20 02:00 UTC, ChloeSartorelli commented on code/Controller/AssetAdminOpen.php
> +        $this->extend('updateApiRead', $data, $request);
```suggestion
        $this->extend('updateApiRead', $data, $file ?? null, $request);
```
Save people the effort of re-fetching the file (presumably if they're updating the data, they're updating it for that specific file)

2024-08-20 02:00 UTC, ChloeSartorelli commented on code/Controller/AssetAdminOpen.php
> +        }
An ID of 0 should _always_ result in a 400 error, because 0 is never a valid ID for a record which means it's a bad request by definition.

```suggestion
        if ($id === 0) {
            $this->jsonError(400);
        }
```

2024-08-20 02:00 UTC, ChloeSartorelli commented on code/Controller/AssetAdminOpen.php
> +        $parents = [];
```suggestion
        bool $includeAncestors,
        bool $includeChildren,
    ): array {
        // Ancestors - used for breadcrumbs
        $ancestors = [];
```

It's not just the parent of the file, it's all ancestors. This tends to be the language used elsewhere, e.g. see the `Hierarchy` extension in framework.

2024-08-20 02:00 UTC, ChloeSartorelli commented on code/Controller/AssetAdminOpen.php
> +            $parents = array_reverse($parents);
```suggestion
            $ancestors = $file->getAncestors();
```

2024-08-20 02:00 UTC, ChloeSartorelli commented on code/Controller/AssetAdminOpen.php
> +        if ($includeChildren) {
I haven't looked at all of the code below - but it seems likely you can use the `Children()`, `AllChildren()`, or `getDescendantIDList()` method here, and use regular ORM filter, limit/offset, and sort functionality.

2024-08-20 02:00 UTC, ChloeSartorelli commented on code/Controller/AssetAdminOpen.php
> +        /** @var File|Versioned $file */
Probably better to just put `@param File|Versioned $file` in the PHPDoc for the method instead of putting this way down here. Otherwise if we want versioning methods higher up in the method in the future we'd have to move the `@var`.

2024-08-20 02:00 UTC, ChloeSartorelli commented on code/Controller/AssetAdminOpen.php
Please add PHPDoc comments to all public and protected methods in this class which aren't inherited from superclasses.

2024-08-20 02:00 UTC, ChloeSartorelli commented on code/Controller/AssetAdminOpen.php
> +            'category' => $file instanceof Folder ? 'folder' : $file->appCategory(),
"folder" isn't a category - what's that for?
We already have the type as folder further down, so this should probably be null or an empty string for non-files.

2024-08-20 02:00 UTC, ChloeSartorelli commented on code/Controller/AssetAdminOpen.php
> +            'published' => $file->isPublished(),
Why do we have both `draft` and `published`? Surely it's only ever one or the other?
Should we have a "versionState" instead, [like we did for linkfield](https://github.com/silverstripe/silverstripe-linkfield/blob/ed8455648d9e2612115a30fe8d6c211c4e7f69f0/src/Models/Link.php#L170-L187)? Maybe even centralise that logic so we can reuse it anywhere we need the version state?

2024-08-20 02:00 UTC, ChloeSartorelli commented on code/Controller/AssetAdminOpen.php
> +    }
This seems completely superfluous. Just call `getFileByID()` directly instead.
```suggestion
```

2024-08-20 02:00 UTC, ChloeSartorelli commented on code/Controller/AssetAdminOpen.php
> +    protected function getFileByID(int $id, bool $isFolder = false, bool $use404 = true): ?File
PHPDoc should explain why we'd ever want `$use404` to be false

2024-08-20 02:00 UTC, ChloeSartorelli commented on code/Controller/AssetAdminOpen.php
> +    protected function getGetDataValue(HTTPRequest $request, string $key, bool $allowMissing = false): mixed
```suggestion
    protected function getDataValue(HTTPRequest $request, string $key, bool $allowMissing = false): mixed
```
I don't think we need to distinguish that this is for a GET request here. `getGet` looks like a typo so it's doing more harm than good.

2024-08-20 02:00 UTC, ChloeSartorelli commented on code/Controller/AssetAdminOpen.php
> +    protected function getGetDataValue(HTTPRequest $request, string $key, bool $allowMissing = false): mixed
Maybe `getValueFromRequest` is better. Much clearer what's happening, imo. And then if you really want the fact that it's a GET request specifically to be in there, you can have `getValueFromGetRequest`

2024-08-20 02:00 UTC, ChloeSartorelli commented on code/Controller/AssetAdminOpen.php
> +            $this->jsonError(404);
```suggestion
            $this->jsonError(400);
```
404 is "we couldn't find the data on _our_ end". In this case the request didn't send the data we need, so it's a bad request.

2024-08-20 02:00 UTC, ChloeSartorelli commented on code/Controller/AssetAdminOpen.php
> +            $this->jsonError(404);
Same with the other errors in this method - in all of them it's the request that didn't send the necessary data (or send it in the wrong format), so it's a bad request.


We haven't even started _looking_ for records on our end yet so it can't be a 404.

2024-08-20 02:00 UTC, ChloeSartorelli commented on code/Controller/AssetAdminOpen.php
> +    private function getThumbnail(File $file): ?string
```suggestion
    private function getSmallThumbnailUrl(File $file): ?string
    {
        $width = UploadField::config()->uninherited('thumbnail_width');
        $height = UploadField::config()->uninherited('thumbnail_height');
        return $this->getThumbnailGenerator()->generateThumbnailLink($file, $width, $height);
    }

    private function getThumbnailUrl(File $file): ?string
```
We're getting a URL, not the actual thumbmnail itself.

2024-08-20 02:00 UTC, ChloeSartorelli commented on code/Controller/AssetAdminOpen.php
> +                $this->httpError(400);
```suggestion
                $this->httpError(404);
```
404 - we looked for the records and we couldn't find them. The request itself was fine.

2024-08-20 02:00 UTC, ChloeSartorelli commented on code/Controller/AssetAdminOpen.php
> +            $list = new ArrayList([new Folder([
```suggestion
            $list = ArrayList::create([Folder::create([
```

2024-08-20 02:00 UTC, ChloeSartorelli commented on code/Controller/AssetAdminOpen.php
> +        } elseif (isset($filter['id']) && (int)$filter['id'] === 0) {
What about `if (isset($filter['id']) && $filter['id'] < 0)` or is otherwise not coercable into an int? That should throw a 400.

2024-08-20 02:00 UTC, ChloeSartorelli commented on code/Controller/AssetAdminOpen.php
> +                $list = new ArrayList([new Folder([
```suggestion
            $fromDate = DateField::create(null, null, $filter['lastEditedFrom']);
            $list = $list->filter("LastEdited:GreaterThanOrEqual", $fromDate->dataValue().' 00:00:00');
            $search = true;
        }
        if (!empty($filter['lastEditedTo'])) {
            $toDate = DateField::create(null, null, $filter['lastEditedTo']);
            $list = $list->filter("LastEdited:LessThanOrEqual", $toDate->dataValue().' 23:59:59');
            $search = true;
        }
        // Date filtering created
        if (!empty($filter['createdFrom'])) {
            $fromDate = DateField::create(null, null, $filter['createdFrom']);
            $list = $list->filter("Created:GreaterThanOrEqual", $fromDate->dataValue().' 00:00:00');
            $search = true;
        }
        if (!empty($filter['createdTo'])) {
            $toDate = DateField::create(null, null, $filter['createdTo']);
            $list = $list->filter("Created:LessThanOrEqual", $toDate->dataValue().' 23:59:59');
            $search = true;
        }
        // Categories (mapped to extensions through the enum type automatically)
        if (!empty($filter['appCategory'])) {
            $list = $list->filter('Name:EndsWith', $filter['appCategory']);
            $search = true;
        }
        // Filter unknown id by known child if search is not applied
        if (!$search && isset($filter['anyChildId'])) {
            $child = File::get()->byID($filter['anyChildId']);
            $id = $child ? ($child->ParentID ?: 0) : 0;
            if ($id) {
                $list = $list->filter('ID', $id);
            } else {
                // Special case for root folder, since filter by ID = 0 will return an empty list
                $list = ArrayList::create([Folder::create([
```

2024-08-20 02:00 UTC, ChloeSartorelli commented on code/Controller/AssetAdminOpen.php
> +                $list = new ArrayList([new Folder([
Did you copy most of this from somewhere?

If so we can leave it more-or-less as is for now and refactor later. But if this is all new code we should just set up `serachable_fields` and use `SearchContext` instead now.

2024-08-20 02:00 UTC, ChloeSartorelli commented on code/Controller/AssetAdmin.php
> +                    'method' => 'POST',
There's a mix between uppercase and lowercase for the method. We should make it consistent - looks like it used to be lowercase so presumably that's what all the other controllers are using too.

2024-08-20 02:00 UTC, ChloeSartorelli commented on code/Controller/AssetAdmin.php
> +            $id = (int) $id;
```suggestion
```
No need to explicitly cast - PHP is quite happy for us to pass string reprensentations of ints around even to methods with strong typing - it'll cast for us.

2024-08-20 02:00 UTC, ChloeSartorelli commented on code/Controller/AssetAdmin.php
> +            $this->jsonError(404);
```suggestion
            $this->jsonError(400);
```
As mentioned elsewhere, at this stage we haven't tried to find records so we can't say we didn't find them. It's just a bad request.

2024-08-20 02:00 UTC, ChloeSartorelli commented on code/Controller/AssetAdmin.php
> +            $this->jsonError(404);
Shouldn't we be using `getGetDataValue()` here instead?

2024-08-20 02:00 UTC, ChloeSartorelli commented on code/Controller/AssetAdmin.php
> +        }
Abstract this into a `getFilesByID()` method similar to the `getFileByID()` method in the `AssetAdminOpen` class.

2024-08-20 02:00 UTC, ChloeSartorelli commented on code/Controller/AssetAdmin.php
> +            if (is_a($file, Folder::class) || !$file->hasExtension(RecursivePublishable::class)) {
> `is_a($file, Folder::class)`

Is it even valid to pass IDs of folders into this request, if we're ignoring them? Shouldn't we return a 400 here instead?

> `!$file->hasExtension(RecursivePublishable::class)`

Extensions are added by class, not by instance or record, so we can probably just check this up front and potentially save some db calls.

2024-08-20 02:00 UTC, ChloeSartorelli commented on code/Controller/AssetAdmin.php
> +                        "$class.OWNER_WARNING",
```suggestion
                $data[] = [
                    'id' => $liveFile->ID,
                    'count' => $count,
                    'message' => _t(
                        __CLASS__ . '.OWNER_WARNING',
```
Just use a new key

2024-08-20 02:00 UTC, ChloeSartorelli commented on code/Controller/AssetAdmin.php
> +    }
We're doing lots of repeated checks like the below after calling this method - just embed those checks into this method instead (mirroring `AssetAdminOpen::getGetDataValue()`)
```php
        if (!is_array($ids) || empty($ids)) {
            $this->jsonError(400);
        }
```

2024-08-20 02:00 UTC, ChloeSartorelli commented on code/Controller/AssetAdminOpen.php
> +    protected function getGetDataValue(HTTPRequest $request, string $key, bool $allowMissing = false): mixed
**UPDATE** Looks like you have `getPostedJsonValue` in `AssetAdmin` - so I recommend the following:

|old name|new name|
|---|---|
|getGetDataValue|getValueFromGetRequest|
|getPostedJsonValue|getValueFromPostRequest|

Then it's clear how these methods relate to each other, and it's really clear what they're doing.

2024-08-20 02:00 UTC, GuySartorelli commented on code/Controller/AssetAdmin.php
> +            $this->jsonError(400);
We decided this was 400 instead of 404 because the data is in the post body rather than the "resource" AKA URL, right?

Probably worth adding a code comment explaining that, because I still look at this and go "but we didn't find it, so it's 404"

2024-08-20 02:00 UTC, GuySartorelli commented on code/Controller/AssetAdmin.php
> +    public function apiArchive(HTTPRequest $request): HTTPResponse
Should probably be `apiDelete` - versioning is technically an add-on which changes the delete behaviour, rather than being the default.

2024-08-20 02:00 UTC, GuySartorelli commented on code/Controller/AssetAdmin.php
> +        }
I think looping through twice like this will run the query twice, won't it? Is there a way we can avoid that?

Same thing with all other methods you've added where that's happening.

2024-08-20 02:00 UTC, GuySartorelli commented on code/Controller/AssetAdmin.php
Please add PHPDoc comments to all new public and protected methods in this class which aren't inherited from superclasses.

2024-08-20 02:00 UTC, GuySartorelli commented on code/Controller/AssetAdmin.php
> +        return $this->jsonSuccess(204);
Why not 200?

2024-08-20 02:00 UTC, GuySartorelli commented on code/Controller/AssetAdmin.php
> +        $folderID = (int) $this->getPostedJsonValue($request, 'folderID');
```suggestion
        $folderID = $this->getPostedJsonValue($request, 'folderID');
```
We don't need to cast it, PHP will do that for us when relevant.

2024-08-20 02:00 UTC, GuySartorelli commented on code/Controller/AssetAdmin.php
> +        }
`getFileByID` already does this 
```suggestion
```

2024-08-20 02:00 UTC, GuySartorelli commented on code/Controller/AssetAdmin.php
> +            $file->write();
The GraphQL resolver did an explicit `$file->writeToStage(Versioned::DRAFT);` - why are we doing a full `write()` here?

2024-08-20 02:00 UTC, GuySartorelli commented on code/Controller/AssetAdmin.php
> +    public function apiPublish(HTTPRequest $request): HTTPResponse
In at least one other place we're checking if files have the `PublishRecursive` extension - but here we're not. We should be consistent and either always check for it before relying on it, or always implicitly assuming it's there.

`silverstripe/versioned` isn't a dependency of this module so we should probably always check.

2024-08-20 02:00 UTC, GuySartorelli commented on code/Controller/AssetAdmin.php
> +        return $this->jsonSuccess(204);
Same question applies for `apiPublish` and `apiUnpublish` and likely others.

2024-08-20 02:00 UTC, GuySartorelli commented on code/Controller/AssetAdmin.php
> +        // CSRF check - note that token is sent in POST body, not header
We should probably change that - but if that's not related to this work say so and I'll create a spin-off card.

2024-08-20 02:00 UTC, GuySartorelli commented on code/Controller/AssetAdmin.php
> +    public function apiUploadFile(HTTPRequest $request): HTTPResponse
If we're adding return types, probably add to `apiCreateFile` as well, and any others I've not noticed are currently missing them.

2024-08-20 02:00 UTC, GuySartorelli commented on code/Controller/AssetAdmin.php
>       * @return HTTPRequest|HTTPResponse
```suggestion
```

2024-08-20 02:00 UTC, GuySartorelli commented on code/Controller/AssetAdmin.php
> +
```suggestion

```
Remove the horizontal space

2024-08-20 02:00 UTC, GuySartorelli commented on tests/behat/features/manage-files.feature
> +      And I press the Archive button inside the modal
It should only say "archive" if `keep_archived_assets` is set to true. We did an exercise in https://github.com/silverstripe/silverstripe-asset-admin/pull/1378 to ensure "delete" and "archive" were used appropriately based on whether files are kept or not.

2024-08-20 05:27 UTC, emteknetnz commented on _config/config.yml
> +      ThumbnailGenerator: '%$SilverStripe\AssetAdmin\Model\ThumbnailGenerator.assetadmin'
Have set to false and added your comments as inline comments

2024-08-20 05:31 UTC, emteknetnz commented on client/src/components/UploadField/UploadField.js
> -    }),
Done

2024-08-20 05:37 UTC, emteknetnz commented on client/src/containers/AssetAdmin/AssetAdmin.js
Previously graphql was a HOC around AssetAdmin (readFilesQuery I believe) and it did the equivalent of refetchFolder a whole lot (though not enough, we have very longstanding bugs with Apollo caching). I don't actually know exactly what triggered it, that's part of the mystery that is the GraphQL HOC / Apollo.

2024-08-20 05:39 UTC, emteknetnz commented on client/src/containers/AssetAdmin/AssetAdmin.js
> +        return response;
From memory this was do to with editing an individual file/folder. I think I changed the logic around to handle both navigating to new folder after it's created, and also moving to the new file location after moving it. Something along those lines.

2024-08-20 05:42 UTC, emteknetnz commented on client/src/containers/AssetAdmin/AssetAdmin.js
> +    return backend.post(url, {
There was some old config that has .method on them, though honestly it's pretty pointless since it just makes the JS harder to read, and we set the required method in $url_handlers so you'll know very quickly if it's typed in wrong

Getting rid of the method would probably require refactoring some other JS code that does dynamically use those methods and that's very unrelated to these PRs

2024-08-20 05:47 UTC, emteknetnz commented on client/src/containers/AssetAdmin/AssetAdmin.js
> +    }
I don't follow? Add what to of all what?

Do you mean throwing Errors? There's plenty of methods doing that in this class

2024-08-20 05:48 UTC, emteknetnz commented on client/src/containers/AssetAdmin/AssetAdmin.js
> +    // return <h1>{ JSON.stringify(this.state.folder) }</h1>;
Removed

2024-08-20 05:49 UTC, emteknetnz commented on client/src/containers/AssetAdmin/AssetAdmin.js
> +    }
this.state.folder is set to null in the constructor.  It's set to non-null in refetchFolder(), though that's an XHR request to there's a brief period early on where this.state.folder is null.

2024-08-20 05:50 UTC, emteknetnz commented on client/src/containers/AssetAdmin/AssetAdmin.js
> +          {folder && <AssetAdminBreadcrumb {...breadcrumbProps} />}
Because folder (which is just this.state.folder) can be null

2024-08-20 05:54 UTC, emteknetnz commented on client/src/containers/AssetAdmin/AssetAdmin.js
> -  graphQLErrors: PropTypes.arrayOf(PropTypes.string),
Updated

2024-08-20 06:07 UTC, emteknetnz commented on client/src/containers/BulkDeleteConfirmation/BulkDeleteConfirmation.js
> - * This avoid firing off a GraphQL query for nothing.
Have added back in "This avoid firing off a GraphQL query for nothing.", as that's still true

2024-08-20 06:09 UTC, emteknetnz commented on client/src/containers/BulkDeleteConfirmation/BulkDeleteConfirmation.js
> - */
Updated. It's still true expect for the Apollo bit which I've removed

2024-08-20 06:10 UTC, emteknetnz commented on code/Controller/AssetAdmin.php
> +    private static $allowed_actions = array(
Updated

2024-08-20 06:10 UTC, emteknetnz commented on code/Controller/AssetAdmin.php
> +    );
Updated

2024-08-20 06:11 UTC, emteknetnz commented on code/Controller/AssetAdmin.php
> +                    'method' => 'POST',
Changed to lowercase

2024-08-20 06:13 UTC, emteknetnz commented on code/Controller/AssetAdmin.php
> +            $id = (int) $id;
Updated

2024-08-20 06:22 UTC, emteknetnz commented on code/Controller/AssetAdmin.php
> +            /* @var Folder&AssetAdminFile $file */
Updated

2024-08-20 06:23 UTC, emteknetnz commented on code/Controller/AssetAdmin.php
Done

2024-08-20 06:28 UTC, emteknetnz commented on code/Controller/AssetAdmin.php
> +            $this->jsonError(404);
We had this discussion offline the other day where I remember correctly we decided that data passed by query string, and hence the URL, for GET requests, which is the case here, is part of the HTTP "resource" and 404 would be correct response.

Whereas for POST request the data is passed in the request body and is not part of the "resource", so 400 is appropriate there.

I do think that's correct as broadly speaking, as for instance a CDN would cache a GET response making no differentiation between a path and a query string, it's all just part of the URL

2024-08-20 06:40 UTC, emteknetnz commented on code/Controller/AssetAdmin.php
> +            $this->jsonError(404);
Updated

2024-08-20 06:45 UTC, emteknetnz commented on code/Controller/AssetAdmin.php
> +            if (is_a($file, Folder::class) || !$file->hasExtension(RecursivePublishable::class)) {
> Is it even valid to pass IDs of folders into this request, if we're ignoring them? Shouldn't we return a 400 here instead?

Yes it's valid, there's nothing stopping a user from selecting them in the file manager along with a bunch of regular file

> Extensions are added by class, not by instance or record, so we can probably just check this up front and potentially save some db calls.

Projects may have several subclasses of File, some of which do and some of which don't have the extension

2024-08-20 06:53 UTC, emteknetnz commented on code/Controller/AssetAdmin.php
> +        }
Done

2024-08-20 06:54 UTC, emteknetnz commented on code/Controller/AssetAdmin.php
> +                        "$class.OWNER_WARNING",
Done

2024-08-20 06:55 UTC, emteknetnz commented on code/Controller/AssetAdmin.php
> +        /* @var Folder&AssetAdminFile $file */
Updated

2024-08-20 06:57 UTC, emteknetnz commented on code/Controller/AssetAdmin.php
> +    public function apiArchive(HTTPRequest $request): HTTPResponse
Updated

2024-08-20 07:00 UTC, emteknetnz commented on code/Controller/AssetAdmin.php
> +            $this->jsonError(400);
I don't think we should be documenting why we use the correct HTTP status codes - that's already defined in elsewhere on the internet

2024-08-20 07:04 UTC, emteknetnz commented on code/Controller/AssetAdmin.php
> +        }
Probably will, though if we fail a permission check half-way through the list of files, looping twice prevents only some of the records being deleted. That would be an awkward situation, because then you'd need to display both a success and failure toast.

Given we're displaying paginated results and not deleting thousands of records at a time, I think the performance penalty as felt by the content editor is going to be miniscule

2024-08-20 07:06 UTC, emteknetnz commented on code/Controller/AssetAdmin.php
> +        $folderID = (int) $this->getPostedJsonValue($request, 'folderID');
Updated

2024-08-20 07:06 UTC, emteknetnz commented on code/Controller/AssetAdmin.php
> +        }
Updated

2024-08-20 07:09 UTC, emteknetnz commented on code/Controller/AssetAdmin.php
> +            $file->write();
From what I can tell there's no functional difference from calling `$file->writeToStage(Versioned::DRAFT)` and regular `$file->write()` other than a calling a couple of extension hooks `onBeforeWriteToStage` and `onAfterWriteToStage`, but those doesn't seem relevant to moving files.  

Maybe graphql has some weird "Live mode" or something so it needed to explicitly have things to draft mode?

I think it's much cleaner just using regular $file->write()

2024-08-20 07:19 UTC, emteknetnz commented on code/Controller/AssetAdmin.php
> +        return $this->jsonSuccess(204);
204 "No Content" mean success with an empty response body.  I've consistently used this as the success code for write requests

2024-08-20 07:27 UTC, emteknetnz commented on code/Controller/AssetAdmin.php
> +        // CSRF check - note that token is sent in POST body, not header
That's a pretty broad topic, because we put SecurityID in as a hidden field all over the place :-)

I don't think this is worth changing at this stage honestly, if/when we go fully API driven that's would be good time to look at this

2024-08-20 07:30 UTC, emteknetnz commented on code/Controller/AssetAdmin.php
> +    public function apiPublish(HTTPRequest $request): HTTPResponse
I'd say assume it's always there, there's just so much UI in asset-admin that assumes things are Versioned there really zero support for unversioned files in practice. Will remove the check to see if a file has the RecursivePublishable extension

2024-08-20 07:41 UTC, emteknetnz commented on code/Controller/AssetAdmin.php
> +    public function apiUploadFile(HTTPRequest $request): HTTPResponse
Done. I've also removed the redundant `return null` underneath the $this->jsonError(400) as they're unreachable code and just make the response type look like it should be nullable when it doesn't need to be

2024-08-20 07:42 UTC, emteknetnz commented on code/Controller/AssetAdmin.php
> +
Done

2024-08-20 22:32 UTC, emteknetnz commented on client/src/containers/Editor/Editor.js
> +  }
https://github.com/silverstripe/silverstripe-asset-admin/pull/1477/files#r1722712939

2024-08-20 22:35 UTC, emteknetnz commented on client/src/containers/Editor/Editor.js
> -    const { file } = this.props;
We're not passing in the file as a prop.  The component is constructed in AssetAdmin.js `<EditorComponent ...>` there's no file prop

2024-08-20 22:35 UTC, emteknetnz commented on client/src/containers/Editor/Editor.js
> +  // file: fileShape,
Removed

2024-08-20 22:37 UTC, emteknetnz commented on client/src/containers/Gallery/Gallery.js
> -              ))}
Error message comes from redux - see mapStateToProps

2024-08-20 22:44 UTC, emteknetnz commented on code/Controller/AssetAdminOpen.php
Done

2024-08-20 22:45 UTC, emteknetnz commented on code/Controller/AssetAdminOpen.php
> +    private static $required_permission_codes = false;
Yes, class extends LeftAndMain which enforces authentication

2024-08-20 22:45 UTC, emteknetnz commented on code/Controller/AssetAdminOpen.php
> +    private static $ignore_menuitem = true;
Updated

2024-08-20 22:46 UTC, emteknetnz commented on code/Controller/AssetAdminOpen.php
> +    protected $thumbnailGenerator;
Updated

2024-08-20 22:46 UTC, emteknetnz commented on code/Controller/AssetAdminOpen.php
> +    // }
Removed

2024-08-20 22:47 UTC, emteknetnz commented on code/Controller/AssetAdminOpen.php
> +                    'url' => Controller::join_links($baseLink, 'api/read'),
Updated

2024-08-20 22:50 UTC, emteknetnz commented on code/Controller/AssetAdminOpen.php
> +            $data['children'] = $tmp['children'];
Comment seems wrong, have changed to "The root folder has an ID of 0"

2024-08-20 22:51 UTC, emteknetnz commented on code/Controller/AssetAdminOpen.php
> +        $this->extend('updateApiRead', $data, $request);
Updated

2024-08-20 22:56 UTC, emteknetnz commented on code/Controller/AssetAdminOpen.php
> +        $parents = [];
Updated

2024-08-20 23:02 UTC, emteknetnz commented on code/Controller/AssetAdminOpen.php
> +            $parents = array_reverse($parents);
Updated to use $file->getAncestors(), though kept the bit where we call `$this->getFileData($parent, $request, false, false);` because we use that to build the returned json

2024-08-20 23:07 UTC, emteknetnz commented on code/Controller/AssetAdminOpen.php
> +        if ($includeChildren) {
I don't think it's that simple due to nuanced way the 3 different scenarios need to behave, and that Folders need to be sorted before files. I don't think we'd reduce much code even if we used those method. I'd rather not alter this right now.

2024-08-20 23:09 UTC, emteknetnz commented on code/Controller/AssetAdminOpen.php
> +        /** @var File|Versioned $file */
I don't like the idea of putting having solitary docblock `@params`, it seems like it goes against how we're generally dealing with adding strong types.  These inline `@vars` are only to support type hinting, and they're easy enough to move up higher if needed in the future

2024-08-20 23:12 UTC, emteknetnz commented on code/Controller/AssetAdminOpen.php
> +            'category' => $file instanceof Folder ? 'folder' : $file->appCategory(),
There's bunch of existing JS logic that looks at `category === 'folder'` including in components not included in this PR. Refactoring that is out of scope

2024-08-20 23:13 UTC, emteknetnz commented on code/Controller/AssetAdminOpen.php
> +            'published' => $file->isPublished(),
There's existing JS logic for things like versioned state badges that relies on this. I don't want to refactor that in this PR

2024-08-20 23:24 UTC, emteknetnz commented on code/Controller/AssetAdminOpen.php
> +    protected function getFileByID(int $id, bool $isFolder = false, bool $use404 = true): ?File
Have changed so that the param is now required and is $missingFileErrorCode - reads a lot better when calling because the 404 or 400 is an argument e.g. `$file = $this->getFileByID($id, false, 404);`

2024-08-20 23:31 UTC, emteknetnz commented on code/Controller/AssetAdminOpen.php
> +        }
If it's a GET request then it should be a 404 - the ID is part of the URL/resource

2024-08-20 23:33 UTC, emteknetnz commented on code/Controller/AssetAdminOpen.php
> +    }
Removed

2024-08-20 23:34 UTC, emteknetnz commented on code/Controller/AssetAdminOpen.php
> +    protected function getGetDataValue(HTTPRequest $request, string $key, bool $allowMissing = false): mixed
Have changed to `getQueryStringValue()` instead

2024-08-20 23:35 UTC, emteknetnz commented on code/Controller/AssetAdminOpen.php
> +            $this->jsonError(404);
As mentioned in other comments, 404 because it's a GET request and the query string is part of the URL/resource

2024-08-20 23:36 UTC, emteknetnz commented on code/Controller/AssetAdminOpen.php
> +        }
0 is the ID used for the rootFolder

2024-08-20 23:46 UTC, emteknetnz commented on code/Controller/AssetAdminOpen.php
> +            $this->jsonError(404);
Using 404 as the general error code for GET requests

2024-08-20 23:48 UTC, emteknetnz commented on code/Controller/AssetAdminOpen.php
> +    private function getThumbnail(File $file): ?string
Updated

2024-08-20 23:49 UTC, emteknetnz commented on code/Controller/AssetAdminOpen.php
> +                $this->httpError(400);
Updated

2024-08-20 23:52 UTC, emteknetnz commented on code/Controller/AssetAdminOpen.php
> +        } elseif (isset($filter['id']) && (int)$filter['id'] === 0) {
Have added ctype_digit() check above

2024-08-20 23:53 UTC, emteknetnz commented on code/Controller/AssetAdminOpen.php
> +            $list = new ArrayList([new Folder([
Updated

2024-08-20 23:54 UTC, emteknetnz commented on code/Controller/AssetAdminOpen.php
> +                $list = new ArrayList([new Folder([
Updated. Yes copied from elsewhere

2024-08-21 00:10 UTC, emteknetnz commented on tests/behat/features/manage-files.feature
> +      And I press the Archive button inside the modal
Updated

2024-08-22 04:44 UTC, GuySartorelli requested changes

2024-08-22 04:44 UTC, GuySartorelli commented on _config/config.yml
> +      ThumbnailGenerator: '%$SilverStripe\AssetAdmin\Model\ThumbnailGenerator.assetadminopen'
Since AssetAdmin is a subclass of AssetAdminOpen, this will result in overriding the thumbnail generator for AssetAdmin.

I haven't tested this yet, but it seems like that would mean a bunch of operations that shouldn't be creating thumbnails now will be?

2024-08-22 04:44 UTC, GuySartorelli commented on client/src/components/UploadField/UploadField.js
> +  endpoints: PropTypes.object,
Wrong place - this should be nested inside `data`

2024-08-22 04:44 UTC, GuySartorelli commented on client/src/containers/AssetAdmin/AssetAdmin.js
> +    }
Sorry, that wasn't very well explained of me lol. I meant add validation of the fileIDs to all of the `do*` functions. We should either consistently do that everywhere or consistently not bother.

2024-08-22 04:44 UTC, GuySartorelli commented on client/src/containers/Editor/Editor.js
> -    const { file } = this.props;
We are passing the file as a prop to `FormBuilderLoaderComponent` right below this.
The comment specifically is about that:
> Passing `file` to FormBuilderLoader will force a re-render...

2024-08-22 04:44 UTC, GuySartorelli commented on client/src/containers/Gallery/Gallery.js
> -              ))}
Right, and that was already happening. I'm asking if that includes the errors that _used_ to be in `graphQLErrors`.
If it doesn't include those, do we have an equivalent set of errors that used to be in `graphQLErrors`?

2024-08-22 04:44 UTC, GuySartorelli commented on code/Controller/AssetAdminOpen.php
> +        /** @var File|Versioned $file */
Any time we have additional information about a param beyond what the name and strong typehint can provide, the PHP docblock is used for that purpose. That's exactly the sort of thing `@param` is for.

2024-08-22 04:44 UTC, GuySartorelli commented on code/Controller/AssetAdminOpen.php
> +            'category' => $file instanceof Folder ? 'folder' : $file->appCategory(),
Ahh fair enough. That's a shame.

2024-08-22 04:44 UTC, GuySartorelli commented on code/Controller/AssetAdminOpen.php
> +            'published' => $file->isPublished(),
Darn. But fair enough.

2024-08-22 04:44 UTC, GuySartorelli commented on code/Controller/AssetAdminOpen.php
> +    protected function getGetDataValue(HTTPRequest $request, string $key, bool $allowMissing = false): mixed
That's better than `getget` at least

2024-08-22 04:44 UTC, GuySartorelli commented on code/Controller/AssetAdmin.php
> +            $this->jsonError(404);
Still isn't using it? (now called `getQueryStringValue()`)

2024-08-22 04:44 UTC, GuySartorelli commented on code/Controller/AssetAdmin.php
> +            $this->jsonError(400);
It's not though - not in a way that gives a clear objective correct code to use for these scenarios. That's why we had such long discussions about it :p

2024-08-22 04:44 UTC, GuySartorelli commented on code/Controller/AssetAdmin.php
> +        }
Good point about the pagination, it's probably okay given that.

2024-08-22 04:44 UTC, GuySartorelli commented on code/Controller/AssetAdmin.php
> +        return $this->jsonSuccess(204);
Love how MDN doesn't really clarify that lol. I'll allow it.

2024-08-22 04:44 UTC, GuySartorelli commented on code/Controller/AssetAdmin.php
> +            $file->write();
Fair

2024-08-22 04:44 UTC, GuySartorelli commented on code/Controller/AssetAdminOpen.php
> +            // c) Filter with currentFolderOnly - descendant files
Probably each of these scenarios should be its own private method, to keep things tidy.

Right now to parse what this method is doing, I have to parse this whole method and keep all of it in my head.

If these three separate scenarios are their own private methods, I can look at them in isolation, and only keep a summary of them in my head when looking at this method.

2024-08-22 07:49 UTC, emteknetnz commented on _config/config.yml
> +      ThumbnailGenerator: '%$SilverStripe\AssetAdmin\Model\ThumbnailGenerator.assetadminopen'
Seems fine to me:

*app/_confing.php*
```php
var_dump([
    SilverStripe\AssetAdmin\Controller\AssetAdmin::create()->getThumbnailGenerator()->getGenerates(),
    SilverStripe\AssetAdmin\Controller\AssetAdminOpen::create()->getThumbnailGenerator()->getGenerates()
]);
die;
// array(2) { [0]=> bool(true) [1]=> bool(false) } 
```

2024-08-22 07:51 UTC, emteknetnz commented on client/src/components/UploadField/UploadField.js
> +  endpoints: PropTypes.object,
Updated

2024-08-22 07:53 UTC, emteknetnz commented on client/src/containers/AssetAdmin/AssetAdmin.js
> +    }
Removed

2024-08-22 07:56 UTC, emteknetnz commented on client/src/containers/Editor/Editor.js
> -    const { file } = this.props;
No longer relevant, at the top of the render method we have

```js
    if (!this.state.file) {
      return null;
    }
```

2024-08-22 07:59 UTC, emteknetnz commented on client/src/containers/Gallery/Gallery.js
> -              ))}
I'm not sure what graphQLErrors actually was, best I can tell it was an apollo thing

2024-08-22 08:03 UTC, emteknetnz commented on code/Controller/AssetAdminOpen.php
> +        /** @var File|Versioned $file */
Updated

2024-08-22 08:12 UTC, emteknetnz commented on code/Controller/AssetAdminOpen.php
> +            // c) Filter with currentFolderOnly - descendant files
I've moved the confusing filtering stuff to a single private method `getFilteredChildFiles()`, I think it makes it a lot clearer having that isolated from everything else

2024-08-22 08:14 UTC, emteknetnz commented on code/Controller/AssetAdmin.php
> +            $this->jsonError(404);
Updated

2024-08-23 00:51 UTC, GuySartorelli commented
Few problems found while testing edge cases:

1. It seems like list view in the asset admin isn't using thumbnails. If I delete the thumbnail variants and then view the list view, I still see the image. If I right click on it and view image in new tab, it's the original full resolution image.
1. If `AssetAdminOpen::apiRead()` throws a json error, the asset admin doesn't load correctly and I see this in the dev console (yes it does just end abruptly - there's no more info other than a js stack trace):
    ```text
    Uncaught (in promise) Error: 
    ```
1. if `AssetAdmin::apiReadDescendantCounts()` throws a json error, the confirm deletion modal is stuck loading with the same error as above in the dev console

I stopped checking at that point - it seems likely that all of the endpoints suffer from similar problems.
I didn't check elemental, but suspect it would probably have the same type of problems.

2024-08-25 23:18 UTC, emteknetnz commented
> It seems like list view in the asset admin isn't using thumbnails. If I delete the thumbnail variants and then view the list view, I still see the image. If I right click on it and view image in new tab, it's the original full resolution image.

Replicated this on 5.2, so looks like it's an existing issue

2024-08-28 23:47 UTC, GuySartorelli commented on client/src/containers/Gallery/Gallery.js
> -              ))}
Looks like this was probably doing what the jsonerror responses are now doing. That is discussed separately from this discussion thread so I'll mark resolved.

2024-08-29 01:08 UTC, GuySartorelli requested changes
The new json error handling is great! 

Found one problem when testing this time around.

## Cannot cancel deleting a file

1. Upload a file.
2. Select the file.
3. Click the `...` button
4. Click delete
5. Try to cancel the modal (it won't go away, and there's no errors in the console, no network requests, nothing)

The fact this wasn't caught by behat means we are missing a test scenario for this.

2024-08-29 04:38 UTC, emteknetnz commented
Have fixed and added behat tests for cancelling and closing the modal

2024-09-02 03:17 UTC, GuySartorelli approved these changes
LGTM, works as expected locally.

2024-09-02 04:33 UTC, merged