ENH Don't emit deprecation warnings for unavoidable API calls
silverstripe/silverstripe-asset-admin pull request #1483
Opened 2024-08-13 23:36 UTC by GuySartorelli

`Versioned::canArchive()` is deprecated in https://github.com/silverstripe/silverstripe-versioned/pull/461

We can't stop calling it directly until CMS 6 because people may have implemented extensions that update the result of this permission check.

## Issue
- https://github.com/silverstripe/silverstripe-versioned/issues/447

2024-08-13 23:58 UTC, GuySartorelli commented
behat CI failure is pre-existing and not related to this PR

2024-08-14 03:02 UTC, emteknetnz requested changes

2024-08-14 03:02 UTC, emteknetnz commented on code/GraphQL/Resolvers/AssetAdminResolver.php
> +            if (Deprecation::withNoReplacement(fn() => $file->canArchive($member))) {
```suggestion
            $canArchive = Deprecation::withNoReplacement(fn() => $item->canArchive());
            if ($canArchive) {
```
Makes this a lot easier to read

2024-08-14 03:24 UTC, GuySartorelli commented on code/GraphQL/Resolvers/AssetAdminResolver.php
> +            if (Deprecation::withNoReplacement(fn() => $file->canArchive($member))) {
Done

2024-08-14 06:42 UTC, emteknetnz approved these changes

2024-08-15 02:56 UTC, merged