API Deprecate GraphQL
silverstripe/silverstripe-asset-admin pull request #1484
Opened 2024-08-15 02:34 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-admin/issues/1799

2024-08-18 21:21 UTC, GuySartorelli requested changes

2024-08-18 21:21 UTC, GuySartorelli commented on code/GraphQL/FileFilter.php
> +            Deprecation::notice('5.3.0', 'Will be moved to the silverstripe/graphql module in CMS 6', Deprecation::SCOPE_CLASS);
```suggestion
 * @deprecated 5.3.0 Will be moved to the silverstripe/graphql module
 */
class FileFilter
{
    public function __construct()
    {
        Deprecation::withNoReplacement(function () {
            Deprecation::notice('5.3.0', 'Will be moved to the silverstripe/graphql module', Deprecation::SCOPE_CLASS);
```

When we did the deprecations for CMS 5, we decided to be fairly standardised in the messages, and part of that was to not include a reference to the specific major release we expect the change to happen in.

Please make this change to other deprecation warnings in this PR and in the related PRs.

2024-08-18 21:38 UTC, emteknetnz commented on code/GraphQL/FileFilter.php
> +            Deprecation::notice('5.3.0', 'Will be moved to the silverstripe/graphql module in CMS 6', Deprecation::SCOPE_CLASS);
Updated

2024-08-19 02:04 UTC, GuySartorelli approved these changes
LGTM

2024-08-19 02:05 UTC, merged