ENH Use FieldValidator for FormFields
silverstripe/silverstripe-asset-admin pull request #1508
Opened 2024-10-31 23:35 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-framework/issues/11422

2024-11-20 22:40 UTC, GuySartorelli requested changes

2024-11-20 22:40 UTC, ChloeSartorelli commented on code/Forms/UploadField.php
> +        $this->beforeExtending('updateValidate', function () use ($result) {
```suggestion
        $this->beforeExtending('updateValidate', function (ValidationResult $result)) {
```

2024-11-20 22:40 UTC, ChloeSartorelli commented on code/Forms/UploadField.php
> +        return $result->combineAnd(parent::validate());
```suggestion
        return parent::validate();
```

2024-11-21 04:59 UTC, emteknetnz commented on code/Forms/UploadField.php
> +        return $result->combineAnd(parent::validate());
Updated

2024-11-21 04:59 UTC, emteknetnz commented on code/Forms/UploadField.php
> +        $this->beforeExtending('updateValidate', function () use ($result) {
Updated

2024-11-25 00:04 UTC, GuySartorelli approved these changes
LGTM, will merge when all PRs are ready

2024-12-02 20:12 UTC, GuySartorelli approved these changes
LGTM

2024-12-02 20:13 UTC, merged