API Deprecate campaign admin integrations
silverstripe/silverstripe-asset-admin pull request #1514
Opened 2024-11-21 06:06 UTC by emteknetnz

Issue https://github.com/silverstripeltd/product-issues/issues/884

2024-11-21 21:58 UTC, GuySartorelli commented on code/Extensions/CampaignAdminExtension.php
> +        Deprecation::notice('5.4.0', 'Will be removed without equivalent functionality to replace it', Deprecation::SCOPE_CLASS);
Use the `noticeWithoutReplacement` so it gets wrapped. Anything without a replacement should be wrapped.

2024-11-25 23:50 UTC, GuySartorelli requested changes

2024-11-25 23:50 UTC, ChloeSartorelli commented on code/Extensions/CampaignAdminExtension.php
> +        Deprecation::notice('5.4.0', 'Will be removed without equivalent functionality to replace it', Deprecation::SCOPE_CLASS);
Use the `noticeWithNoReplacment` so it gets wrapped. Anything without a replacement should be wrapped.
```suggestion
       Deprecation::noticeWithNoReplacment('5.4.0', scope: Deprecation::SCOPE_CLASS);
```

2024-11-25 23:50 UTC, ChloeSartorelli requested changes

2024-11-25 23:50 UTC, GuySartorelli commented on code/Extensions/CampaignAdminExtension.php
> +        Deprecation::notice('5.4.0', 'Will be removed without equivalent functionality to replace it', Deprecation::SCOPE_CLASS);
```suggestion
 * @deprecated 2.4.0 Will be removed without equivalent functionality to replace it
 */
class CampaignAdminExtension extends Extension
{
    public function __construct()
    {
        Deprecation::notice('2.4.0', 'Will be removed without equivalent functionality to replace it', Deprecation::SCOPE_CLASS);
```

2024-11-25 23:50 UTC, GuySartorelli commented on code/Extensions/CampaignAdminExtension.php
> +        Deprecation::notice('5.4.0', 'Will be removed without equivalent functionality to replace it', Deprecation::SCOPE_CLASS);
`2.4.0` not `5.4.0`

2024-11-25 23:57 UTC, emteknetnz commented on code/Extensions/CampaignAdminExtension.php
> +        Deprecation::notice('5.4.0', 'Will be removed without equivalent functionality to replace it', Deprecation::SCOPE_CLASS);
Updated

2024-11-25 23:57 UTC, emteknetnz commented on code/Extensions/CampaignAdminExtension.php
> +        Deprecation::notice('5.4.0', 'Will be removed without equivalent functionality to replace it', Deprecation::SCOPE_CLASS);
Updated

2024-11-25 23:59 UTC, GuySartorelli commented on code/Extensions/CampaignAdminExtension.php
> +        Deprecation::notice('5.4.0', 'Will be removed without equivalent functionality to replace it', Deprecation::SCOPE_CLASS);
You missed the PHPDoc

2024-11-26 00:26 UTC, emteknetnz commented on code/Extensions/CampaignAdminExtension.php
> +        Deprecation::notice('5.4.0', 'Will be removed without equivalent functionality to replace it', Deprecation::SCOPE_CLASS);
Opps, done

2024-11-26 01:05 UTC, GuySartorelli approved these changes
LGTM

2024-11-26 01:05 UTC, merged