DEP Replace react-dnd with dnd-kit
silverstripe/silverstripe-asset-admin pull request #1527
Opened 2024-12-17 23:01 UTC by GuySartorelli

This PR replaces the `react-dnd` with `dnd-kit` with like-for-like functionality

## Issue
- https://github.com/silverstripe/.github/issues/343

2024-12-19 01:35 UTC, GuySartorelli commented on client/src/containers/Gallery/GalleryDND.js
Note that I didn't split converting this or other components to functional as its own PR or commit because the lifycycle functions needed to be removed anyway. Converting it with the lifecycle events in-tact and then removing them separately would have been more work.

2024-12-19 01:35 UTC, GuySartorelli commented on client/src/containers/Gallery/GalleryDND.js
> +      <DndContext sensors={sensors} onDragStart={handleDragStart} onDragEnd={handleDragEnd} modifiers={[snapCenterToCursor]}>
I tried using built-in modifiers (including `restrictToWindowEdges`) to restrict where we can drag the files, but none of them worked how I'd expect them to, so I opted to go without. The end result is the same unbound dragging as the old approach so it's not worse than it was before, at least.

2024-12-19 01:35 UTC, GuySartorelli commented on client/src/components/GalleryItem/GalleryItem.js
> +    }
Needed for styling the draglayer for folders

2024-12-19 01:35 UTC, GuySartorelli commented on client/src/components/GalleryItem/GalleryItem.scss
> +  background: transparent url("../../images/icon_archive.png") center center no-repeat;
These changes were required to fix a problem where the background was being drawn over top of the border of the drag layer.
Note that I can't just use `background-image` because that seems to be overridden by something else.

2024-12-19 01:35 UTC, GuySartorelli commented on client/src/components/GalleryItem/GalleryItemDragLayer.js
> -  }
Offset stuff is handled by the `snapCenterToCursor` modifier now

2024-12-19 01:35 UTC, GuySartorelli commented on client/src/components/GalleryItem/README.md
> +<GalleryItem item={{id: 2, exists: true, type: 'folder', category: 'folder'}} selectable={true} />
While updating styling, I had to render out these directly so I could mess with css in the browser.
I found that just an ID wasn't enough, so I've updated for an example for a file and for a folder, for future reference.

2024-12-19 01:35 UTC, GuySartorelli commented on client/src/components/GalleryItem/draggable.js
> -    },
Handling what happens on drag/drop is done inside `GalleryDND` instead.

2024-12-19 01:35 UTC, GuySartorelli commented on client/src/containers/Gallery/Gallery.js
> +          onDragStartEnd={(dragging) => this.handleEnableDropzone(!dragging)}
Replaces `handleDrag` in `ThumbnailView`

2024-12-19 20:23 UTC, GuySartorelli commented on tests/behat/src/FixtureContext.php
> +    }
I couldn't use the existing `I drag the "some element" element to the "some other element" element` method, because the only selectors available relied on fixed IDs which works locally but fails in CI.

2024-12-19 21:04 UTC, GuySartorelli commented on tests/behat/src/FixtureContext.php
> +    }
I couldn't use the existing `I drag the "some element" element to the "some other element" element` method, because the only selectors available rely on fixed IDs which works locally but fails in CI.

2024-12-19 22:41 UTC, emteknetnz requested changes
Couple of weird things happening when I tested locally in firefox, neither of which happen in CMS 5
- After moving, the thumbnail animates back to its original location
- There's a red toast error when attempting to move to the parent folder. Only happens with moving files, not moving folders.

https://www.youtube.com/watch?v=vnHESa15Q8g

2024-12-19 22:41 UTC, emteknetnz commented on tests/behat/features/drag-and-drop.feature
> +@javascript @assets @retry @job3 @gsat
```suggestion
@javascript @assets @retry @job3
```

2024-12-19 22:44 UTC, GuySartorelli commented
> There's a server error when attempting to move to the parent folder. Only happens with moving files, not moving folders.

If the parent folder is the root, [this is a known regression](https://github.com/silverstripe/silverstripe-asset-admin/issues/1529) that was already linked in the issue description.

2024-12-19 22:56 UTC, emteknetnz commented
Server error still happens when trying to move files to the parent folder in deeply nested folders

2024-12-19 22:59 UTC, GuySartorelli commented
Can't reproduce. Please:
1. Compare against the `3.0` branch without this PR to rule out an existing regression
2. If it _is_ an existing regression, open a new card about it
3. If it _is not_ an existing regression, please provide server error message and stack trace - I may even ask for a copy of your DB and assets since as I said I can't reproduce.

2024-12-19 23:14 UTC, GuySartorelli commented on tests/behat/features/drag-and-drop.feature
> +@javascript @assets @retry @job3 @gsat
Done

2024-12-19 23:15 UTC, GuySartorelli commented
> After moving, the thumbnail animates back to its original location

Good spot. Fixed.

2025-01-06 01:19 UTC, emteknetnz commented
Server error is [this issue](https://github.com/silverstripe/silverstripe-asset-admin/issues/1529)

2025-01-06 01:21 UTC, emteknetnz approved these changes

2025-01-06 01:21 UTC, merged